"""AuditLog — first-class, indexed on (org, timestamp) and (entity_type, entity_id).

This is not a middleware afterthought; ``CLAUDE.md`` requires audit logging
as a first-class table from day 1. Two indexes cover the query shapes the
UI actually needs:

- ``ix_audit_log_org_time`` — the "show me the last 100 events for this
  org" page, which is the most common reviewer view.
- ``ix_audit_log_entity`` — the "show me the history of THIS entity"
  drill-down from any entity detail page.

FK to ``users`` uses ``ondelete="SET NULL"`` rather than CASCADE or
RESTRICT: an audit record outlives the user it was generated by.
Deleting the user must not erase the audit trail — that's the whole
point of an audit log — but keeping the FK lets joins surface the
author when they still exist.

``changes`` is a JSON column (JSONB on Postgres, JSON text on SQLite)
sized to hold small before/after diffs; ``default=dict`` keeps the
empty-case shape predictable.
"""

from __future__ import annotations

import uuid
from datetime import datetime

from sqlalchemy import JSON, DateTime, ForeignKey, Index, String, Uuid
from sqlalchemy.orm import Mapped, mapped_column

from idraa.db import Base
from idraa.models._types import now_utc
from idraa.models.mixins import IdMixin


class AuditLog(IdMixin, Base):
    __tablename__ = "audit_log"
    __table_args__ = (
        Index("ix_audit_log_org_time", "organization_id", "timestamp"),
        Index("ix_audit_log_entity", "entity_type", "entity_id"),
    )

    organization_id: Mapped[uuid.UUID] = mapped_column(
        Uuid(as_uuid=True),
        ForeignKey("organizations.id", ondelete="RESTRICT"),
        nullable=False,
    )
    entity_type: Mapped[str] = mapped_column(String(64), nullable=False)
    entity_id: Mapped[uuid.UUID] = mapped_column(Uuid(as_uuid=True), nullable=False)
    user_id: Mapped[uuid.UUID | None] = mapped_column(
        Uuid(as_uuid=True),
        ForeignKey("users.id", ondelete="SET NULL"),
        nullable=True,
    )
    # create / update / delete / login / logout — short action verb only.
    # Width: String(64). Issue #129 T6 widened from 32→64 after multiple
    # control_function_assignment.* strings exceeded 32 chars (silently
    # accepted by SQLite but would reject on Postgres).
    action: Mapped[str] = mapped_column(String(64), nullable=False)
    changes: Mapped[dict[str, object]] = mapped_column(JSON, default=dict, nullable=False)
    timestamp: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), default=now_utc, nullable=False
    )
    ip_address: Mapped[str | None] = mapped_column(String(45), nullable=True)
