"""phase 1.1.2 orgs users sessions audit

Revision ID: 101fc72c9f38
Revises: 9e459d17c7c3
Create Date: 2026-04-24 15:29:16.083270

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '101fc72c9f38'
down_revision: Union[str, Sequence[str], None] = '9e459d17c7c3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organizations',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('industry_type', sa.Enum('MANUFACTURING', 'HEALTHCARE', 'FINANCIAL', 'TECH', 'ENERGY', 'RETAIL', 'GOVERNMENT', 'EDUCATION', 'OTHER', name='industrytype', native_enum=False), nullable=False),
    sa.Column('industry_sub_sector', sa.String(length=120), nullable=True),
    sa.Column('naics_code', sa.String(length=12), nullable=True),
    sa.Column('organization_size', sa.Enum('SMALL', 'MEDIUM', 'LARGE', 'ENTERPRISE', name='organizationsize', native_enum=False), nullable=False),
    sa.Column('employee_count', sa.Integer(), nullable=True),
    sa.Column('annual_revenue', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('geographic_regions', sa.JSON(), nullable=False),
    sa.Column('headquarters_location', sa.String(length=255), nullable=True),
    sa.Column('security_maturity', sa.Enum('BASIC', 'DEVELOPING', 'DEFINED', 'MANAGED', 'OPTIMIZING', name='securitymaturity', native_enum=False), nullable=False),
    sa.Column('annual_security_budget', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('has_cyber_insurance', sa.Boolean(), nullable=False),
    sa.Column('cyber_insurance_limit', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('cyber_insurance_deductible', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('risk_appetite', sa.Enum('CONSERVATIVE', 'MODERATE', 'AGGRESSIVE', name='riskappetite', native_enum=False), nullable=False),
    sa.Column('compliance_requirements', sa.JSON(), nullable=False),
    sa.Column('regulatory_environment', sa.JSON(), nullable=False),
    sa.Column('technology_stack', sa.JSON(), nullable=False),
    sa.Column('cloud_usage', sa.String(length=32), nullable=True),
    sa.Column('digital_maturity', sa.String(length=32), nullable=True),
    sa.Column('preferred_currency', sa.String(length=3), nullable=False),
    sa.Column('preferred_language', sa.String(length=8), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('ADMIN', 'ANALYST', 'REVIEWER', 'VIEWER', name='userrole', native_enum=False), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'email', name='uq_users_org_email')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=False)
    op.create_index(op.f('ix_users_organization_id'), 'users', ['organization_id'], unique=False)
    op.create_table('audit_log',
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('entity_type', sa.String(length=64), nullable=False),
    sa.Column('entity_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('action', sa.String(length=32), nullable=False),
    sa.Column('changes', sa.JSON(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_audit_log_entity', 'audit_log', ['entity_type', 'entity_id'], unique=False)
    op.create_index('ix_audit_log_org_time', 'audit_log', ['organization_id', 'timestamp'], unique=False)
    op.create_table('auth_sessions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_auth_sessions_user_id'), 'auth_sessions', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_auth_sessions_user_id'), table_name='auth_sessions')
    op.drop_table('auth_sessions')
    op.drop_index('ix_audit_log_org_time', table_name='audit_log')
    op.drop_index('ix_audit_log_entity', table_name='audit_log')
    op.drop_table('audit_log')
    op.drop_index(op.f('ix_users_organization_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('organizations')
    # ### end Alembic commands ###
