"""phase 1.3 scenarios

Revision ID: 1a3794c327d4
Revises: ca534fcbf966
Create Date: 2026-04-26 21:19:02.911029

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1a3794c327d4'
down_revision: Union[str, Sequence[str], None] = 'ca534fcbf966'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scenarios',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('scenario_type', sa.Enum('TEMPLATE', 'CUSTOM', 'INDUSTRY_STANDARD', name='scenariotype', native_enum=False), nullable=False),
    sa.Column('threat_category', sa.String(length=64), nullable=False),
    sa.Column('threat_actor_type', sa.String(length=64), nullable=True),
    sa.Column('attack_vector', sa.String(length=128), nullable=True),
    sa.Column('asset_class', sa.String(length=128), nullable=True),
    sa.Column('threat_event_frequency', sa.JSON(), nullable=False),
    sa.Column('vulnerability', sa.JSON(), nullable=False),
    sa.Column('primary_loss', sa.JSON(), nullable=False),
    sa.Column('secondary_loss', sa.JSON(), nullable=True),
    sa.Column('iris_calibration_year', sa.Integer(), nullable=False),
    sa.Column('industry', sa.String(length=64), nullable=False),
    sa.Column('revenue_tier', sa.String(length=64), nullable=False),
    sa.Column('calibration_override_pin', sa.JSON(), nullable=True),
    sa.Column('overlay_pins', sa.JSON(), nullable=False),
    sa.Column('source', sa.Enum('EXPERT_JUDGMENT', name='scenariosource', native_enum=False), nullable=False),
    sa.Column('last_simulated_at', sa.DateTime(), nullable=True),
    sa.Column('last_simulation_inputs_hash', sa.String(length=64), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'ACTIVE', 'DEPRECATED', 'DELETED', name='entitystatus', native_enum=False), nullable=False),
    sa.Column('version', sa.String(length=32), nullable=False),
    sa.Column('row_version', sa.Integer(), nullable=False, server_default=sa.text("1")),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scenarios_organization_id'), 'scenarios', ['organization_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_scenarios_organization_id'), table_name='scenarios')
    op.drop_table('scenarios')
    # ### end Alembic commands ###
