"""run presentation fx snapshot

Revision ID: 1a5eb1814c32
Revises: be495e8b34d3
Create Date: 2026-06-15 09:56:55.459726

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1a5eb1814c32'
down_revision: Union[str, Sequence[str], None] = 'be495e8b34d3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('risk_analysis_runs', sa.Column('presentation_fx_snapshot', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('risk_analysis_runs', 'presentation_fx_snapshot')
    # ### end Alembic commands ###
