"""phase 1.2 controls

Revision ID: 355450b21719
Revises: 101fc72c9f38
Create Date: 2026-04-25 00:46:29.419770

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '355450b21719'
down_revision: Union[str, Sequence[str], None] = '101fc72c9f38'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('controls',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('domain', sa.Enum('LOSS_EVENT', 'VARIANCE_MANAGEMENT', 'DECISION_SUPPORT', name='controldomain', native_enum=False), nullable=False),
    sa.Column('function', sa.Enum('PREVENTIVE', 'DETECTIVE', 'CORRECTIVE', 'COMPENSATING', name='controlfunction', native_enum=False), nullable=False),
    sa.Column('type', sa.Enum('TECHNICAL', 'ADMINISTRATIVE', 'PHYSICAL', name='controltype', native_enum=False), nullable=False),
    sa.Column('control_strength', sa.Float(), nullable=False),
    sa.Column('control_reliability', sa.Float(), nullable=False),
    sa.Column('control_coverage', sa.Float(), nullable=False),
    sa.Column('cost_model', sa.JSON(), nullable=False),
    sa.Column('nist_csf_functions', sa.JSON(), nullable=False),
    sa.Column('iso_27001_domains', sa.JSON(), nullable=False),
    sa.Column('compliance_mappings', sa.JSON(), nullable=False),
    sa.Column('skill_requirements', sa.JSON(), nullable=False),
    sa.Column('technology_dependencies', sa.JSON(), nullable=False),
    sa.Column('applicable_industries', sa.JSON(), nullable=False),
    sa.Column('applicable_org_sizes', sa.JSON(), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'ACTIVE', 'DEPRECATED', 'DELETED', name='entitystatus', native_enum=False), nullable=False),
    sa.Column('version', sa.String(length=32), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_controls_organization_id'), 'controls', ['organization_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_controls_organization_id'), table_name='controls')
    op.drop_table('controls')
    # ### end Alembic commands ###
