"""add fx_rates

Revision ID: 42c65b63ceeb
Revises: 5af21ffc0c4b
Create Date: 2026-06-14 20:59:07.529816

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '42c65b63ceeb'
down_revision: Union[str, Sequence[str], None] = '5af21ffc0c4b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fx_rates',
    sa.Column('code', sa.String(length=3), nullable=False),
    sa.Column('usd_rate', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('as_of_date', sa.Date(), nullable=False),
    sa.Column('source', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.CheckConstraint('length(code) = 3', name='ck_fx_rate_code_len'),
    sa.CheckConstraint('usd_rate >= 0.000001 AND usd_rate <= 100000', name='ck_fx_rate_range'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fx_rates_organization_id'), 'fx_rates', ['organization_id'], unique=False)
    op.create_index('ux_fx_rate_active_per_code', 'fx_rates', ['organization_id', 'code'], unique=True, sqlite_where=sa.text('is_active = 1'), postgresql_where=sa.text('is_active = TRUE'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ux_fx_rate_active_per_code', table_name='fx_rates', sqlite_where=sa.text('is_active = 1'), postgresql_where=sa.text('is_active = TRUE'))
    op.drop_index(op.f('ix_fx_rates_organization_id'), table_name='fx_rates')
    op.drop_table('fx_rates')
    # ### end Alembic commands ###
