"""Issue #203: map seventeen seed library entries' industry strings onto IndustryType
(spec docs/superpowers/specs/2026-10-09-issue-203-seed-industries-design.md §3.2).

Same shape as c7d2e9f4a1b3_issue_209_community_remaps.py: frozen literals, three-way
per-cell classification against the current DB value (already / apply / drift),
per-slug atomicity, guarded downgrade, pinned counter line. One table, _CHANGES, over
two JSON columns (``applicable_industries``, ``calibration_anchor``); there is no re-map
table and no lookup against another table. JSON cells are compared on the DECODED value
(list equality / dict equality), never on the stored text.

Revision ID: 512d010c5760
Revises: c7d2e9f4a1b3
Create Date: 2026-10-09
"""

from __future__ import annotations

import json
import logging
from typing import Literal

import sqlalchemy as sa
from alembic import op

revision = "512d010c5760"
down_revision = "c7d2e9f4a1b3"
branch_labels = None
depends_on = None

logger = logging.getLogger("alembic.runtime.migration")

_ALLOWED_COLUMNS: frozenset[str] = frozenset({"applicable_industries", "calibration_anchor"})
_JSON_COLUMNS: frozenset[str] = frozenset({"applicable_industries", "calibration_anchor"})

# Generated by scripts/build_issue_203_migration_table.py against merge-base
# 5fe95ff0 (idraa/main after #238). 27 cells across 17 slugs, sorted by (slug, column).
_CHANGES: tuple[tuple[str, str, object, object], ...] = (
    (
        "branch-atm-physical-tamper",
        "applicable_industries",
        ["finance_and_insurance"],
        ["financial"],
    ),
    (
        "branch-atm-physical-tamper",
        "calibration_anchor",
        {
            "industry": "finance_and_insurance",
            "revenue_tier": "100m_to_1b",
            "vuln_posture": "inherent (control-naive) per fair-cam-methodology 'Vulnerability anchor' — ATM USB ports not disabled; hard drive not encrypted; cabinet tamper switches not monitored; no ATM integrity-monitoring software (Wincor/Diebold security suite absent)",
            "loss_anchor": "unbounded analyst PERT — ATM jackpotting outside the IRIS cyber-loss corpus. Primary PERT reasoned from physical hardware constraints: single-machine cash dispense $20K–$200K per cassette (industry estimate); mode $150K reflects coordinated multi-machine attack on a branch; high $1.5M reflects a regional campaign of 8–10 machines. Financial IRIS (p50=$1M, p95=$194M) explicitly NOT applied — those figures reflect all-incident cyber losses including ransomware tail; applying them would materially overclaim for a physically-bounded cash-dispense event. Secondary = hardware replacement + field-engineer + regulatory reporting ~27% of primary.",
        },
        {
            "industry": "financial",
            "revenue_tier": "100m_to_1b",
            "vuln_posture": "inherent (control-naive) per fair-cam-methodology 'Vulnerability anchor' — ATM USB ports not disabled; hard drive not encrypted; cabinet tamper switches not monitored; no ATM integrity-monitoring software (Wincor/Diebold security suite absent)",
            "loss_anchor": "unbounded analyst PERT — ATM jackpotting outside the IRIS cyber-loss corpus. Primary PERT reasoned from physical hardware constraints: single-machine cash dispense $20K–$200K per cassette (industry estimate); mode $150K reflects coordinated multi-machine attack on a branch; high $1.5M reflects a regional campaign of 8–10 machines. Financial IRIS (p50=$1M, p95=$194M) explicitly NOT applied — those figures reflect all-incident cyber losses including ransomware tail; applying them would materially overclaim for a physically-bounded cash-dispense event. Secondary = hardware replacement + field-engineer + regulatory reporting ~27% of primary.",
        },
    ),
    (
        "education-campus-facility-tamper",
        "applicable_industries",
        ["education_services"],
        ["education"],
    ),
    (
        "education-campus-facility-tamper",
        "calibration_anchor",
        {
            "industry": "education_services",
            "revenue_tier": "100m_to_1b",
            "vuln_posture": "inherent (control-naive) per fair-cam-methodology 'Vulnerability anchor' — no tamper alerting on network-infrastructure cabinets; campus buildings rely on standard mechanical locks; no physical intrusion detection in server rooms or comms closets; no camera monitoring of IT infrastructure locations",
            "loss_anchor": "unbounded analyst PERT — campus physical facility tampering outside the IRIS cyber-loss corpus. Primary PERT reasoned from repair and downtime economics: network-cable repair/replacement $5K–$50K per incident; access-control or server-room disruption with research downtime $50K–$500K; multi-building campaign up to $2M. Education IRIS (p50=$249K, p95=$6M) noted for reference but not applied — IRIS captures cyber incidents, not physical facility tampering. Secondary = emergency response + student/faculty notification + security upgrade planning ~30% of primary.",
        },
        {
            "industry": "education",
            "revenue_tier": "100m_to_1b",
            "vuln_posture": "inherent (control-naive) per fair-cam-methodology 'Vulnerability anchor' — no tamper alerting on network-infrastructure cabinets; campus buildings rely on standard mechanical locks; no physical intrusion detection in server rooms or comms closets; no camera monitoring of IT infrastructure locations",
            "loss_anchor": "unbounded analyst PERT — campus physical facility tampering outside the IRIS cyber-loss corpus. Primary PERT reasoned from repair and downtime economics: network-cable repair/replacement $5K–$50K per incident; access-control or server-room disruption with research downtime $50K–$500K; multi-building campaign up to $2M. Education IRIS (p50=$249K, p95=$6M) noted for reference but not applied — IRIS captures cyber incidents, not physical facility tampering. Secondary = emergency response + student/faculty notification + security upgrade planning ~30% of primary.",
        },
    ),
    (
        "education-research-ip-exfiltration",
        "applicable_industries",
        ["education_services"],
        ["education"],
    ),
    (
        "education-research-ip-exfiltration",
        "calibration_anchor",
        {
            "industry": "education_services",
            "revenue_tier": "100m_to_1b",
            "vuln_posture": "inherent (control-naive) per fair-cam-methodology 'Vulnerability anchor' — no network segmentation of research servers; researcher workstations unmanaged; no DLP or outbound data monitoring on research repositories",
            "loss_anchor": "sanity-bounded against Education IRIS (IRIS 2025 Figure A3, p.35, Education sector p50=$249K, p95=$6M). Analyst PERT primary reflects incident-response + remediation costs (financiable component); mode $350K above IRIS Education p50=$249K — consistent with a larger research department or multi-year campaign exposure; high $3M near IRIS p95 ($6M), appropriate for extended discovery of a sustained intrusion. The strategic R&D-value-destruction component is qualitatively dominant but not captured in financial loss distributions and is excluded from the PERT. Secondary = regulatory/grant compliance + notification + reputational impact ~29% of primary. Unbounded analyst PERT for the IP-value component — nation-state R&D IP exfiltration outside the IRIS cyber-loss corpus.",
        },
        {
            "industry": "education",
            "revenue_tier": "100m_to_1b",
            "vuln_posture": "inherent (control-naive) per fair-cam-methodology 'Vulnerability anchor' — no network segmentation of research servers; researcher workstations unmanaged; no DLP or outbound data monitoring on research repositories",
            "loss_anchor": "sanity-bounded against Education IRIS (IRIS 2025 Figure A3, p.35, Education sector p50=$249K, p95=$6M). Analyst PERT primary reflects incident-response + remediation costs (financiable component); mode $350K above IRIS Education p50=$249K — consistent with a larger research department or multi-year campaign exposure; high $3M near IRIS p95 ($6M), appropriate for extended discovery of a sustained intrusion. The strategic R&D-value-destruction component is qualitatively dominant but not captured in financial loss distributions and is excluded from the PERT. Secondary = regulatory/grant compliance + notification + reputational impact ~29% of primary. Unbounded analyst PERT for the IP-value component — nation-state R&D IP exfiltration outside the IRIS cyber-loss corpus.",
        },
    ),
    (
        "energy-billing-system-tamper",
        "applicable_industries",
        ["utilities", "energy"],
        ["utilities"],
    ),
    (
        "financial-call-center-social-eng",
        "applicable_industries",
        ["finance_and_insurance"],
        ["financial"],
    ),
    (
        "financial-call-center-social-eng",
        "calibration_anchor",
        {
            "industry": "finance_and_insurance",
            "revenue_tier": "100m_to_1b",
            "vuln_posture": "inherent (control-naive) per fair-cam-methodology 'Vulnerability anchor' — no voice biometrics or knowledge-based authentication for high-risk transactions; agents trained on basic verification scripts only; no real-time transaction-velocity anomaly detection at the call center authorization layer; single-factor voice verification bypassable via pretexting",
            "loss_anchor": "sanity-bounded against Financial IRIS (IRIS 2025 Figure A3, p.35, Financial sector p50=$1M, p95=$194M). Analyst PERT primary reflects authorized-transfer fraud + customer remediation: mode $200K plausible for a targeted vishing campaign resulting in one to several successful fraudulent transfers (per-complaint avg IC3 2024 fraud categories $10K–$50K; institutional loss per event higher due to aggregation across call center scale); high $5M well below IRIS p95. Secondary = regulatory + CS remediation + customer compensation ~25% of primary. No per-org call-center vishing loss distribution found (C-iii-b T2b negative outcome catalogued).",
        },
        {
            "industry": "financial",
            "revenue_tier": "100m_to_1b",
            "vuln_posture": "inherent (control-naive) per fair-cam-methodology 'Vulnerability anchor' — no voice biometrics or knowledge-based authentication for high-risk transactions; agents trained on basic verification scripts only; no real-time transaction-velocity anomaly detection at the call center authorization layer; single-factor voice verification bypassable via pretexting",
            "loss_anchor": "sanity-bounded against Financial IRIS (IRIS 2025 Figure A3, p.35, Financial sector p50=$1M, p95=$194M). Analyst PERT primary reflects authorized-transfer fraud + customer remediation: mode $200K plausible for a targeted vishing campaign resulting in one to several successful fraudulent transfers (per-complaint avg IC3 2024 fraud categories $10K–$50K; institutional loss per event higher due to aggregation across call center scale); high $5M well below IRIS p95. Secondary = regulatory + CS remediation + customer compensation ~25% of primary. No per-org call-center vishing loss distribution found (C-iii-b T2b negative outcome catalogued).",
        },
    ),
    (
        "financial-transaction-tampering",
        "applicable_industries",
        ["finance_and_insurance"],
        ["financial"],
    ),
    (
        "financial-transaction-tampering",
        "calibration_anchor",
        {
            "industry": "finance_and_insurance",
            "revenue_tier": "100m_to_1b",
            "vuln_posture": "inherent (control-naive) per fair-cam-methodology 'Vulnerability anchor' — no dual-control enforcement on privileged-access transaction modifications; no real-time anomaly detection on wire transfers; no segregation of initiation and approval roles for privileged users",
            "loss_anchor": "sanity-bounded against Financial IRIS (IRIS 2025 Figure A3, p.35, Financial sector p50=$1M, p95=$194M). Analyst PERT primary reflects direct-funds-diversion-dominant loss: mode $500K plausible for an operations-level insider with branch/department transaction authority; high $10M reflects a privileged-system-level insider (settlements desk, correspondent banking); high well below IRIS p95. Secondary = audit + regulatory + remediation ~30% of primary. No per-org loss distribution for insider financial transaction tampering found (C-iii-b T2b negative outcome catalogued).",
        },
        {
            "industry": "financial",
            "revenue_tier": "100m_to_1b",
            "vuln_posture": "inherent (control-naive) per fair-cam-methodology 'Vulnerability anchor' — no dual-control enforcement on privileged-access transaction modifications; no real-time anomaly detection on wire transfers; no segregation of initiation and approval roles for privileged users",
            "loss_anchor": "sanity-bounded against Financial IRIS (IRIS 2025 Figure A3, p.35, Financial sector p50=$1M, p95=$194M). Analyst PERT primary reflects direct-funds-diversion-dominant loss: mode $500K plausible for an operations-level insider with branch/department transaction authority; high $10M reflects a privileged-system-level insider (settlements desk, correspondent banking); high well below IRIS p95. Secondary = audit + regulatory + remediation ~30% of primary. No per-org loss distribution for insider financial transaction tampering found (C-iii-b T2b negative outcome catalogued).",
        },
    ),
    ("gov-citizen-portal-ddos", "applicable_industries", ["public", "government"], ["public"]),
    ("gov-employee-insider-leak", "applicable_industries", ["public", "government"], ["public"]),
    ("gov-records-tampering", "applicable_industries", ["public", "government"], ["public"]),
    (
        "healthcare-record-alteration",
        "applicable_industries",
        ["health_care_and_social_assistance"],
        ["healthcare"],
    ),
    (
        "healthcare-record-alteration",
        "calibration_anchor",
        {
            "industry": "health_care_and_social_assistance",
            "revenue_tier": "100m_to_1b",
            "vuln_posture": "inherent (control-naive) per fair-cam-methodology 'Vulnerability anchor' — no EHR audit-log monitoring or alerting on anomalous record modification patterns; minimum-necessary access policy not enforced; no separation between record-read and record-modify privileges for clinical staff",
            "loss_anchor": "sanity-bounded against Healthcare IRIS (IRIS 2025 Figure A3, p.35, Healthcare sector p50=$557K, p95=$14M). Analyst PERT primary reflects billing-fraud + malpractice-liability-dominant loss: mode $250K plausible for a mid-scale insider billing fraud scheme; high $5M reflects a sustained scheme with patient-harm malpractice claims; high well below IRIS p95. Secondary = HIPAA OCR + remediation + reputation ~40% of primary (regulatory tail elevated for data-integrity violations vs. breach). No per-org loss distribution for insider EHR record alteration found (C-iii-b T2b negative outcome catalogued).",
        },
        {
            "industry": "healthcare",
            "revenue_tier": "100m_to_1b",
            "vuln_posture": "inherent (control-naive) per fair-cam-methodology 'Vulnerability anchor' — no EHR audit-log monitoring or alerting on anomalous record modification patterns; minimum-necessary access policy not enforced; no separation between record-read and record-modify privileges for clinical staff",
            "loss_anchor": "sanity-bounded against Healthcare IRIS (IRIS 2025 Figure A3, p.35, Healthcare sector p50=$557K, p95=$14M). Analyst PERT primary reflects billing-fraud + malpractice-liability-dominant loss: mode $250K plausible for a mid-scale insider billing fraud scheme; high $5M reflects a sustained scheme with patient-harm malpractice claims; high well below IRIS p95. Secondary = HIPAA OCR + remediation + reputation ~40% of primary (regulatory tail elevated for data-integrity violations vs. breach). No per-org loss distribution for insider EHR record alteration found (C-iii-b T2b negative outcome catalogued).",
        },
    ),
    (
        "ip-theft-by-competitor",
        "applicable_industries",
        ["manufacturing", "technology"],
        ["manufacturing", "information"],
    ),
    (
        "logistics-tms-data-tampering",
        "applicable_industries",
        ["transportation_and_warehousing"],
        ["transportation"],
    ),
    (
        "logistics-tms-data-tampering",
        "calibration_anchor",
        {
            "industry": "transportation_and_warehousing",
            "revenue_tier": "100m_to_1b",
            "vuln_posture": "inherent (control-naive) per fair-cam-methodology 'Vulnerability anchor' — TMS credentials shared among dispatchers; no change-audit trail on manifest modifications; no anomaly detection on out-of-pattern route changes",
            "loss_anchor": "sanity-bounded against Transportation IRIS (IRIS 2025 Figure A3, p.35, Transportation sector p50=$490K, p95=$23M). Analyst PERT primary reflects cargo-value-dominant loss: mode $300K plausible for a single diverted full-truckload shipment ($150K–$500K commodity value range per TAPA Cargo Crime Report categories); high $5M well below IRIS p95. Secondary = dispute resolution + regulatory + TMS remediation ~27% of primary. No primary-cited per-org TMS-fraud loss distribution found (C-iii-b T2b negative outcome catalogued).",
        },
        {
            "industry": "transportation",
            "revenue_tier": "100m_to_1b",
            "vuln_posture": "inherent (control-naive) per fair-cam-methodology 'Vulnerability anchor' — TMS credentials shared among dispatchers; no change-audit trail on manifest modifications; no anomaly detection on out-of-pattern route changes",
            "loss_anchor": "sanity-bounded against Transportation IRIS (IRIS 2025 Figure A3, p.35, Transportation sector p50=$490K, p95=$23M). Analyst PERT primary reflects cargo-value-dominant loss: mode $300K plausible for a single diverted full-truckload shipment ($150K–$500K commodity value range per TAPA Cargo Crime Report categories); high $5M well below IRIS p95. Secondary = dispute resolution + regulatory + TMS remediation ~27% of primary. No primary-cited per-org TMS-fraud loss distribution found (C-iii-b T2b negative outcome catalogued).",
        },
    ),
    (
        "logistics-warehouse-physical-intrusion",
        "applicable_industries",
        ["transportation_and_warehousing"],
        ["transportation"],
    ),
    (
        "logistics-warehouse-physical-intrusion",
        "calibration_anchor",
        {
            "industry": "transportation_and_warehousing",
            "revenue_tier": "100m_to_1b",
            "vuln_posture": "inherent (control-naive) per fair-cam-methodology 'Vulnerability anchor' — no tamper alerting on access-control panels; CCTV lacks integrity monitoring; no real-time access-anomaly detection; single-factor badge-based entry only",
            "loss_anchor": "unbounded analyst PERT — physical warehouse intrusion outside the IRIS cyber-loss corpus. Primary PERT reasoned from cargo theft value profiles: TAPA reports high-value cargo thefts typically range $100K–$5M per incident for electronics/pharma; mode $400K reflects mid-tier warehouse cargo density. Transportation IRIS (p50=$490K, p95=$23M) noted for reference but not applied as a bound given IRIS captures cyber-financial incidents, not physical cargo theft events. Secondary = CCTV/access-control remediation + customer penalties + investigation ~25% of primary.",
        },
        {
            "industry": "transportation",
            "revenue_tier": "100m_to_1b",
            "vuln_posture": "inherent (control-naive) per fair-cam-methodology 'Vulnerability anchor' — no tamper alerting on access-control panels; CCTV lacks integrity monitoring; no real-time access-anomaly detection; single-factor badge-based entry only",
            "loss_anchor": "unbounded analyst PERT — physical warehouse intrusion outside the IRIS cyber-loss corpus. Primary PERT reasoned from cargo theft value profiles: TAPA reports high-value cargo thefts typically range $100K–$5M per incident for electronics/pharma; mode $400K reflects mid-tier warehouse cargo density. Transportation IRIS (p50=$490K, p95=$23M) noted for reference but not applied as a bound given IRIS captures cyber-financial incidents, not physical cargo theft events. Secondary = CCTV/access-control remediation + customer penalties + investigation ~25% of primary.",
        },
    ),
    (
        "professional-office-physical-theft",
        "applicable_industries",
        ["professional_and_business_services"],
        ["professional"],
    ),
    (
        "professional-office-physical-theft",
        "calibration_anchor",
        {
            "industry": "professional_and_business_services",
            "revenue_tier": "10m_to_100m",
            "vuln_posture": "inherent (control-naive) per fair-cam-methodology 'Vulnerability anchor' — no full-disk encryption on laptops; no remote-wipe capability; physical office perimeter relies on standard locks with no intrusion monitoring; no data-classification policy distinguishing regulated-PII from general business data on portable devices",
            "loss_anchor": "unbounded analyst PERT — physical office theft outside the IRIS cyber-loss corpus. Primary PERT reasoned from hardware replacement + breach-notification: device replacement $1K–$5K per unit; breach-notification legal + mailing costs $50K–$500K for mid-size firm with client PII exposure; mode $80K reflects 1–2 device theft with limited PII scope. Professional IRIS (p50=$736K, p95=$17M) noted for reference but not applied — IRIS captures cyber incidents, not physical theft. Secondary = client notification + reputation + litigation ~38% of primary.",
        },
        {
            "industry": "professional",
            "revenue_tier": "10m_to_100m",
            "vuln_posture": "inherent (control-naive) per fair-cam-methodology 'Vulnerability anchor' — no full-disk encryption on laptops; no remote-wipe capability; physical office perimeter relies on standard locks with no intrusion monitoring; no data-classification policy distinguishing regulated-PII from general business data on portable devices",
            "loss_anchor": "unbounded analyst PERT — physical office theft outside the IRIS cyber-loss corpus. Primary PERT reasoned from hardware replacement + breach-notification: device replacement $1K–$5K per unit; breach-notification legal + mailing costs $50K–$500K for mid-size firm with client PII exposure; mode $80K reflects 1–2 device theft with limited PII scope. Professional IRIS (p50=$736K, p95=$17M) noted for reference but not applied — IRIS captures cyber incidents, not physical theft. Secondary = client notification + reputation + litigation ~38% of primary.",
        },
    ),
    (
        "retail-ecommerce-checkout-ddos",
        "calibration_anchor",
        {
            "industry": "retail_trade",
            "revenue_tier": "100m_to_1b",
            "vuln_posture": "inherent (control-naive) per fair-cam-methodology 'Vulnerability anchor' — no DDoS scrubbing or CDN-layer absorption; payment API routes directly to origin servers; no traffic-shaping or rate-limiting at the network perimeter",
            "loss_anchor": "sanity-bounded against Retail IRIS (IRIS 2025 Figure A3, p.35, Retail sector p50=$746K, p95=$45M). Analyst PERT primary reflects revenue-disruption-dominant loss: mode $400K reflects 1–4 hours of checkout outage for a mid-market retailer (estimate: $100K/hour during peak season at 10K orders/hr × $100 AOV); high $10M reflects a sustained peak-day attack well below IRIS p95. Secondary = brand damage + customer compensation + expedited CDN deployment ~25% of primary. No per-org DDoS loss distribution for retail e-commerce found (C-iii-b T2b negative outcome catalogued).",
        },
        {
            "industry": "retail",
            "revenue_tier": "100m_to_1b",
            "vuln_posture": "inherent (control-naive) per fair-cam-methodology 'Vulnerability anchor' — no DDoS scrubbing or CDN-layer absorption; payment API routes directly to origin servers; no traffic-shaping or rate-limiting at the network perimeter",
            "loss_anchor": "sanity-bounded against Retail IRIS (IRIS 2025 Figure A3, p.35, Retail sector p50=$746K, p95=$45M). Analyst PERT primary reflects revenue-disruption-dominant loss: mode $400K reflects 1–4 hours of checkout outage for a mid-market retailer (estimate: $100K/hour during peak season at 10K orders/hr × $100 AOV); high $10M reflects a sustained peak-day attack well below IRIS p95. Secondary = brand damage + customer compensation + expedited CDN deployment ~25% of primary. No per-org DDoS loss distribution for retail e-commerce found (C-iii-b T2b negative outcome catalogued).",
        },
    ),
    ("retail-store-employee-fraud", "applicable_industries", ["retail_trade"], ["retail"]),
    (
        "retail-store-employee-fraud",
        "calibration_anchor",
        {
            "industry": "retail_trade",
            "revenue_tier": "10m_to_100m",
            "vuln_posture": "inherent (control-naive) per fair-cam-methodology 'Vulnerability anchor' — no POS transaction anomaly detection; transaction-void authority not segregated from cash-handling; inventory counts not reconciled against POS records; no CCTV monitoring of POS stations",
            "loss_anchor": "sanity-bounded against Retail IRIS (IRIS 2025 Figure A3, p.35, Retail sector p50=$746K, p95=$45M). Analyst PERT primary reflects direct-cash/inventory-loss-dominant profile: mode $80K consistent with ACFE median occupational fraud of $145K across all industries (ACFE 2024 p.7 — used as order-of-magnitude reference, not a per-org distribution anchor); high $1.5M reflects a sustained multi-location scheme; well below IRIS p95. Secondary = investigation + POS remediation + process redesign ~25% of primary. NRF aggregate shrinkage statistics used for plausibility only (aggregate totals prohibited as per-org anchors per C-iii research protocol §1).",
        },
        {
            "industry": "retail",
            "revenue_tier": "10m_to_100m",
            "vuln_posture": "inherent (control-naive) per fair-cam-methodology 'Vulnerability anchor' — no POS transaction anomaly detection; transaction-void authority not segregated from cash-handling; inventory counts not reconciled against POS records; no CCTV monitoring of POS stations",
            "loss_anchor": "sanity-bounded against Retail IRIS (IRIS 2025 Figure A3, p.35, Retail sector p50=$746K, p95=$45M). Analyst PERT primary reflects direct-cash/inventory-loss-dominant profile: mode $80K consistent with ACFE median occupational fraud of $145K across all industries (ACFE 2024 p.7 — used as order-of-magnitude reference, not a per-org distribution anchor); high $1.5M reflects a sustained multi-location scheme; well below IRIS p95. Secondary = investigation + POS remediation + process redesign ~25% of primary. NRF aggregate shrinkage statistics used for plausibility only (aggregate totals prohibited as per-org anchors per C-iii research protocol §1).",
        },
    ),
    (
        "telecom-subscriber-data-breach",
        "applicable_industries",
        ["information", "telecom"],
        ["information"],
    ),
)

_TABLE = sa.table(
    "scenario_library_entries",
    *[sa.column(c) for c in sorted(_ALLOWED_COLUMNS)],
    sa.column("slug"),
    sa.column("version"),
    sa.column("source"),
)


# --- copied verbatim from alembic/versions/c7d2e9f4a1b3_issue_209_community_remaps.py ---
# _validate_changes, _decode, _encode, _classify, _group_by_slug, _classify_slug_group
# (same bodies; only the RuntimeError prefix becomes "issue-203 seed industries:").
# --------------------------------------------------------------------------------------


def _validate_changes(changes: tuple[tuple[str, str, object, object], ...]) -> None:
    """Every column name in `changes` must be a vetted literal from
    _ALLOWED_COLUMNS -- an explicit raise, never an assert (assertions are
    stripped under `python -O`), so a typo'd or malicious column name can
    never reach SQL construction."""
    for slug, column, _old, _new in changes:
        if column not in _ALLOWED_COLUMNS:
            raise RuntimeError(
                f"issue-203 seed industries: column {column!r} (slug {slug!r}) is not in "
                "_ALLOWED_COLUMNS; refusing to build SQL for an unvetted column name"
            )


def _decode(col: str, raw: object) -> object:
    """DB value -> Python value for comparison. JSON columns: None for SQL NULL or the
    JSON literal 'null'; json.loads for a str; passed through unchanged otherwise (a
    backend that already deserializes JSON columns). Text/enum columns: passed through."""
    if col in _JSON_COLUMNS:
        if raw is None or raw == "null":
            return None
        if isinstance(raw, str):
            return json.loads(raw)
        return raw
    return raw


def _encode(col: str, value: object) -> object:
    """Python value -> DB bind value. JSON columns: None stays None (SQL NULL); anything
    else is json.dumps'd. Text/enum columns: passed through unchanged."""
    if col in _JSON_COLUMNS:
        return None if value is None else json.dumps(value)
    return value


def _classify(
    col: str, raw: object, old: object, new: object
) -> Literal["apply", "already", "drift"]:
    """Decode `raw` (the current DB value) and compare to `old`/`new`. `new` is checked
    first: on a fresh DB an inserting migration may already have written `new` from the
    live seed JSON, which must never be mistaken for `old` even if `old` happens to
    parsed-equal `new`'s repr in some degenerate case."""
    current = _decode(col, raw)
    if current == new:
        return "already"
    if current == old:
        return "apply"
    return "drift"


def _group_by_slug(
    changes: tuple[tuple[str, str, object, object], ...],
) -> dict[str, tuple[tuple[str, object, object], ...]]:
    """Groups `changes` by slug, preserving each cell's (column, old, new) and the
    slugs' first-appearance order (== alphabetical, since `_CHANGES` is sorted by
    (slug, column))."""
    groups: dict[str, list[tuple[str, object, object]]] = {}
    for slug, column, old, new in changes:
        groups.setdefault(slug, []).append((column, old, new))
    return {slug: tuple(cells) for slug, cells in groups.items()}


def _classify_slug_group(
    cells: tuple[tuple[str, object, object], ...],
    found_raw: dict[str, tuple[bool, object]],
) -> tuple[dict[str, Literal["apply", "already", "drift"]], tuple[str, ...]]:
    """Per-slug atomicity (inherited verbatim from c7d2e9f4a1b3 — #209 spec §4.1 amendment M4-1): classifies every cell of one
    slug's group first (`cells` as (column, target_from, target_to) -- already
    direction-adjusted by the caller), then enforces the group guard: if ANY cell is
    genuinely "drift" (found but neither `target_from` nor `target_to`) or its row is
    missing (`found_raw[column][0]` is False), every "apply"-eligible cell in the group
    is reclassified to "drift" too (an "already" cell is left as "already" -- it needs
    no write regardless of its siblings). Returns (final per-column classification,
    the columns that were genuinely drifted/missing -- the latter is what a caller logs
    in its one-per-slug warning, never the full reclassified set, so the message names
    only the true anomaly)."""
    raw_classification: dict[str, Literal["apply", "already", "drift"]] = {}
    for column, target_from, target_to in cells:
        found, raw = found_raw[column]
        raw_classification[column] = (
            "drift" if not found else _classify(column, raw, target_from, target_to)
        )
    drifted_columns = tuple(sorted(c for c, cls in raw_classification.items() if cls == "drift"))
    if not drifted_columns:
        return raw_classification, drifted_columns
    final: dict[str, Literal["apply", "already", "drift"]] = {
        column: ("drift" if cls == "apply" else cls) for column, cls in raw_classification.items()
    }
    return final, drifted_columns


def _where(slug: str) -> tuple[sa.ColumnElement[bool], ...]:
    return (_TABLE.c.slug == slug, _TABLE.c.version == 1, _TABLE.c.source == "seed")


def _run(reverse: bool) -> None:
    _validate_changes(_CHANGES)
    bind = op.get_bind()
    applied = already = drift = 0
    label = "downgrade" if reverse else "upgrade"
    for slug, cells in sorted(_group_by_slug(_CHANGES).items()):
        dir_cells = tuple(
            (column, (new, old) if reverse else (old, new)) for column, old, new in cells
        )
        found_raw: dict[str, tuple[bool, object]] = {}
        for column, _targets in dir_cells:
            row = bind.execute(sa.select(_TABLE.c[column]).where(*_where(slug))).first()
            found_raw[column] = (row is not None, row[0] if row is not None else None)
        classification, drifted = _classify_slug_group(
            tuple((column, f, t) for column, (f, t) in dir_cells), found_raw
        )
        if drifted:
            logger.warning(
                "issue-203 seed industries %s: drift in slug=%s; skipping whole slug "
                "(atomic group) -- drifted column(s): %s",
                label,
                slug,
                ", ".join(drifted),
            )
        for column, (_f, target_to) in dir_cells:
            cls = classification[column]
            if cls == "already":
                already += 1
            elif cls == "drift":
                drift += 1
            else:
                bind.execute(
                    sa.update(_TABLE)
                    .where(*_where(slug))
                    .values(**{column: _encode(column, target_to)})
                )
                applied += 1
    if reverse:
        logger.info(
            "issue-203 seed industries downgrade: applied=%d already_old=%d drift=%d",
            applied,
            already,
            drift,
        )
    else:
        logger.info(
            "issue-203 seed industries: applied=%d already_new=%d drift=%d",
            applied,
            already,
            drift,
        )


def upgrade() -> None:
    _run(reverse=False)


def downgrade() -> None:
    _run(reverse=True)
