"""run weight_robustness column

Revision ID: 9ae19de17172
Revises: c4d9a1f3b2e0
Create Date: 2026-06-26 13:42:54.038725

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9ae19de17172'
down_revision: Union[str, Sequence[str], None] = 'c4d9a1f3b2e0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('risk_analysis_runs', sa.Column('weight_robustness', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('risk_analysis_runs', 'weight_robustness')
    # ### end Alembic commands ###
