"""Issue #234: re-word ten ATT&CK crosswalk rationales that quote text #209 superseded
(spec docs/superpowers/specs/2026-10-10-issue-234-crosswalk-rationales-design.md §4.2).

Same shape as 512d010c5760_issue_203_seed_industries.py (itself c7d2e9f4a1b3's): frozen
literals, three-way per-cell classification against the current DB value (already / apply /
drift), per-slug atomicity, guarded downgrade, pinned counter line. One table, _CHANGES, of
six-tuples ``(slug, domain, technique_id, column, old, new)`` over three columns of
``library_entry_attack_mappings`` (``rationale``, ``provenance``, and the JSON list
``citations``); rows are resolved through typed SQLAlchemy Core tables (entry by slug at
version 1 / source 'seed', technique by (technique_id, domain), mapping row by
(library_entry_id, library_entry_version, technique_id)). JSON cells are compared on the
DECODED value, never on the stored text. ``scenario_attack_mappings`` (organisation copies) is
never touched. No log line or exception message carries rationale text.

Revision ID: b00d4a63cd9c
Revises: 512d010c5760
Create Date: 2026-10-10
"""

from __future__ import annotations

import json
import logging
import uuid
from typing import Literal

import sqlalchemy as sa
from alembic import op

revision = "b00d4a63cd9c"
down_revision = "512d010c5760"
branch_labels = None
depends_on = None

logger = logging.getLogger("alembic.runtime.migration")

_ALLOWED_COLUMNS: frozenset[str] = frozenset({"rationale", "provenance", "citations"})
_JSON_COLUMNS: frozenset[str] = frozenset({"citations"})

# Generated by scripts/build_issue_234_migration_table.py against merge-base
# 4efd5387 (idraa/main after #240). 14 cells across 4 slugs, sorted by
# (slug, domain, technique_id, column).
_CHANGES: tuple[tuple[str, str, str, str, object, object], ...] = (
    (
        "higher-ed-insider-ddos",
        "enterprise",
        "T1498",
        "rationale",
        "Entry describes an enrolled affiliate directing 'an external botnet to launch volumetric distributed denial-of-service attacks against a university's own network.' Paras Jha's Mirai-precursor botnet DDoS campaign against Rutgers University's central authentication and registration systems (Nov 2014-Sep 2016) is the documented exemplar, per the DOJ USAO-NJ guilty plea and $8.6M restitution order.",
        "Entry description states that an enrolled affiliate 'directs volumetric distributed denial-of-service attacks against a university's own network' and that 'the capacity is a botnet the student runs, as in the Rutgers case, or a rented DDoS-for-hire (booter) service.' Paras Jha's botnet DDoS campaign against Rutgers University's central authentication and registration systems (Nov 2014-Sep 2016) is the documented exemplar, per the DOJ USAO-NJ guilty plea and $8.6M restitution order.",
    ),
    (
        "hospitality-guest-data-insider",
        "enterprise",
        "T1078",
        "rationale",
        "Entry description states the insider 'abuses privileged access to the property-management system (PMS) or central reservation system' -- the insider's own legitimate PMS/CRS account, not a compromised credential, is the load-bearing access vector; attack_vector=insider_access_abuse.",
        "Entry description states that a malicious insider with ordinary role access 'abuses that access to the property-management system (PMS) or central reservation system' -- an account the front-desk or reservation staff member legitimately holds, not a compromised credential, is the load-bearing access vector; attack_vector=insider_access_abuse.",
    ),
    (
        "insider-ip-theft-manufacturing",
        "enterprise",
        "T1005",
        "rationale",
        "DOJ's press release documents Zheng 'stealing multiple electronic files, including proprietary files involving design models, engineering drawings, configuration files, and material specifications' from GE's internal systems -- collection of sensitive files resident on the corporate file store prior to exfiltration, matching this entry's 'exfiltrates proprietary manufacturing processes, CAD designs, semiconductor mask sets, chemical formulations, or other trade secrets' framing.",
        "Entry description states that the abused access is 'ordinary and role-based' and that 'when a foreign service tasked it (the cited GE case was charged as economic espionage) the sponsor decides the community'; collecting files the insider can read is the same step in the self-initiated case this entry covers. DOJ's press release documents Zheng 'stealing multiple electronic files, including proprietary files involving design models, engineering drawings, configuration files, and material specifications' from GE's internal systems -- collection of sensitive files from systems the insider could read prior to exfiltration, matching this entry's 'exfiltrates proprietary manufacturing processes, CAD designs, semiconductor mask sets, chemical formulations, or other trade secrets' framing.",
    ),
    (
        "insider-ip-theft-manufacturing",
        "enterprise",
        "T1027",
        "citations",
        [
            "U.S. Department of Justice, Office of Public Affairs, 'Former GE Engineer and Chinese Businessman Charged with Economic Espionage and Theft of GE's Trade Secrets' (2019-04-23), https://www.justice.gov/archives/opa/pr/former-ge-engineer-and-chinese-businessman-charged-economic-espionage-and-theft-ge-s-trade (accessed 2026-07-05), paragraph describing the steganographic sunset photo"
        ],
        [
            "U.S. Department of Justice, Office of Public Affairs, 'New York Man Charged With Theft of Trade Secrets' (2018-08-01), https://www.justice.gov/archives/opa/pr/new-york-man-charged-theft-trade-secrets (verified 2026-10-10 against the full-text reprint at https://www.ip-watch.org/2018/08/02/trade-secret-thief-hid-files-digital-photo-sunset/; justice.gov refuses automated fetches), paragraph describing the steganographic sunset photo"
        ],
    ),
    (
        "insider-ip-theft-manufacturing",
        "enterprise",
        "T1027",
        "provenance",
        "cited",
        "expert-estimate",
    ),
    (
        "insider-ip-theft-manufacturing",
        "enterprise",
        "T1027",
        "rationale",
        "DOJ's press release documents Zheng using steganography -- hiding 'data files belonging to GE into an innocuous looking digital picture of a sunset' -- to obfuscate the stolen trade-secret files before transmission, the specific concealment technique behind this entry's IP-exfiltration archetype.",
        "Entry description states that the abused access is 'ordinary and role-based' and places the GE case, 'charged as economic espionage', with the sponsor's community; concealing stolen files before moving them is a step carried over from that case to the self-initiated insider, an estimate rather than a documented behaviour of this entry. DOJ's press release documents Zheng using steganography -- hiding 'data files belonging to GE into an innocuous looking digital picture of a sunset' -- to obfuscate the stolen trade-secret files before transmission.",
    ),
    (
        "insider-ip-theft-manufacturing",
        "enterprise",
        "T1078",
        "rationale",
        "Entry's example_incidents names the 'General Electric IP theft case 2023 (former GE engineer convicted of stealing turbine technology for China)'. DOJ's press release documents that Zheng, 'while employed at GE Power & Water in Schenectady, New York as an engineer specializing in sealing technology,' 'exploited his access to GE's files' -- abuse of his own legitimate employee account, not a compromised credential, is the load-bearing insider vector this entry generalizes to CAD/mask-set/formulation theft.",
        "Entry's example_incidents names the 'General Electric IP theft case 2023 (former GE engineer convicted of stealing turbine technology for China)', a case the description says was 'charged as economic espionage' and places with the sponsor's community. DOJ's press release documents that Zheng, 'while employed at GE Power & Water in Schenectady, New York as an engineer specializing in sealing technology,' 'exploited his access to GE's files' -- use of his own legitimate employee account, not a compromised credential, the same access the self-initiated insider this entry covers abuses ('The access abused is ordinary and role-based').",
    ),
    (
        "insider-ip-theft-manufacturing",
        "enterprise",
        "T1567",
        "citations",
        [
            "U.S. Department of Justice, Office of Public Affairs, 'Former GE Engineer and Chinese Businessman Charged with Economic Espionage and Theft of GE's Trade Secrets' (2019-04-23), https://www.justice.gov/archives/opa/pr/former-ge-engineer-and-chinese-businessman-charged-economic-espionage-and-theft-ge-s-trade (accessed 2026-07-05), paragraph describing the photo being e-mailed to Zheng's personal account"
        ],
        [
            "U.S. Department of Justice, Office of Public Affairs, 'New York Man Charged With Theft of Trade Secrets' (2018-08-01), https://www.justice.gov/archives/opa/pr/new-york-man-charged-theft-trade-secrets (verified 2026-10-10 against the full-text reprint at https://www.ip-watch.org/2018/08/02/trade-secret-thief-hid-files-digital-photo-sunset/; justice.gov refuses automated fetches), paragraph describing the photo being e-mailed to Zheng's e-mail account"
        ],
    ),
    (
        "insider-ip-theft-manufacturing",
        "enterprise",
        "T1567",
        "provenance",
        "cited",
        "expert-estimate",
    ),
    (
        "insider-ip-theft-manufacturing",
        "enterprise",
        "T1567",
        "rationale",
        "DOJ's press release documents Zheng '[e-]mail[ing] the digital picture, which contained the stolen GE data files, to Zheng's e-mail account' -- using a personal webmail service, rather than GE's own infrastructure, as the channel to move the stolen trade secrets out of the corporate environment.",
        "Entry description states that the abused access is 'ordinary and role-based' and places the GE case, 'charged as economic espionage', with the sponsor's community. DOJ's press release documents Zheng '[e-]mail[ing] the digital picture, which contained the stolen GE data files, to Zheng's e-mail account' -- moving the files to his own account outside GE. Exfiltration Over Web Service fits when files leave through an external web service such as personal webmail or cloud storage; this row estimates that the self-initiated insider this entry covers uses such a service, a step the release does not document.",
    ),
    (
        "ot-network-scanning-reconnaissance",
        "enterprise",
        "T1078",
        "rationale",
        "CISA/NSA/FBI advisory AA24-038A states Volt Typhoon 'relies on valid accounts... repeatedly exfiltrates domain credentials, ensuring access to current and valid accounts' for long-term undetected persistence -- the 'persistent pre-positioning reconnaissance... for future disruption capability' this entry's example_incidents attributes to Volt Typhoon.",
        "Entry's example_incidents states 'CISA AA24-038A documented pre-positioning in US water, power, and communications OT networks; attributed to PRC state-sponsored actors for future disruption capability'; the advisory states that Volt Typhoon 'relies on valid accounts' and that the actors 'repeatedly exfiltrate domain credentials, ensuring access to current and valid accounts', for long-term undetected persistence -- valid-account access is how the counted intrusion campaigns extend and keep that pre-positioning once inside.",
    ),
    (
        "ot-network-scanning-reconnaissance",
        "enterprise",
        "T1595",
        "rationale",
        "Entry description states actors conduct 'active probing of exposed ICS protocols (Modbus, DNP3, BACnet, EtherNet/IP)' -- direct-interaction network probing of victim infrastructure, matching Active Scanning as distinct from the passive Shodan/Censys step.",
        "Entry description states 'Scanning — passive (Shodan, Censys) or active protocol enumeration — is not a threat event under the nation-state counting rule and is not counted', and its canonical gap places these steps before any attempt ('Scanning and protocol enumeration come before any attempt and are not counted here'): the actor performs active enumeration of exposed ICS services though the entry does not count it, and the crosswalk records behaviour rather than counted events -- direct-interaction probing of victim infrastructure, matching Active Scanning as distinct from the passive Shodan/Censys step.",
    ),
    (
        "ot-network-scanning-reconnaissance",
        "enterprise",
        "T1596",
        "rationale",
        "Entry description states actors use 'passive scanning (Shodan, Censys)' of OT networks -- T1596 Search Open Technical Databases explicitly covers searching 'public collections of network data/artifacts gathered from traffic and/or scans,' the Shodan/Censys pattern this entry names.",
        "Entry description states 'Scanning — passive (Shodan, Censys) or active protocol enumeration — is not a threat event under the nation-state counting rule and is not counted', and its canonical gap places these steps before any attempt ('Scanning and protocol enumeration come before any attempt and are not counted here'): the passive half is still performed though not counted -- T1596 Search Open Technical Databases covers searching 'public collections of network data/artifacts gathered from traffic and/or scans,' the Shodan/Censys pattern this entry names.",
    ),
    (
        "ot-network-scanning-reconnaissance",
        "ics",
        "T0888",
        "rationale",
        "Entry describes probing of ICS-specific protocols to footprint exposed devices ahead of a follow-on attack -- once probing reaches the OT network itself this is Remote System Information Discovery ('detailed information about remote systems... make/model, role, and configuration... to aid in targeting'), the ICS-domain counterpart to the entry's IT-side scanning steps.",
        "Entry description states 'A loss event is a successful access or theft of documentation' -- T0888 is the discovery step that follows such an access, distinct from the uncounted enumeration that precedes the attempt: once an access attempt against exposed ICS services or engineering workstations succeeds, the pre-positioning the entry attributes to Volt Typhoon footprints the OT network's devices, which is Remote System Information Discovery ('detailed information about remote systems... make/model, role, and configuration... to aid in targeting').",
    ),
)

# Typed Core tables, as a5b6c7d8e9f0 declares them: the sa.Uuid() id columns bind the same
# 32-hex form the ORM writes. The text/JSON cells are deliberately untyped so a JSON cell comes
# back as the stored text and _decode / _encode below are the only (de)serialisation.
_ENTRIES = sa.table(
    "scenario_library_entries",
    sa.column("id", sa.Uuid()),
    sa.column("version", sa.Integer()),
    sa.column("slug"),
    sa.column("source"),
)
_TECHNIQUES = sa.table(
    "attack_techniques",
    sa.column("id", sa.Uuid()),
    sa.column("technique_id"),
    sa.column("domain"),
)
_MAPPINGS = sa.table(
    "library_entry_attack_mappings",
    sa.column("id", sa.Uuid()),
    sa.column("library_entry_id", sa.Uuid()),
    sa.column("library_entry_version", sa.Integer()),
    sa.column("technique_id", sa.Uuid()),
    sa.column("rationale"),
    sa.column("provenance"),
    sa.column("citations"),
)

# A cell key inside one slug's group: (domain, technique_id, column).
_CellKey = tuple[str, str, str]


# --- machinery from alembic/versions/512d010c5760_issue_203_seed_industries.py ---
# _classify, _decode, _encode are copied verbatim; _validate_changes is adapted to the
# six-tuple; _group_by_slug / _classify_slug_group are the same bodies keyed by the cell key
# (domain, technique_id, column) instead of the column, because one slug owns several
# mapping rows. The RuntimeError prefix is "issue-234 crosswalk rationales:".
# ----------------------------------------------------------------------------------------


def _validate_changes(changes: tuple[tuple[str, str, str, str, object, object], ...]) -> None:
    """Every column name in `changes` must be a vetted literal from
    _ALLOWED_COLUMNS -- an explicit raise, never an assert (assertions are
    stripped under `python -O`), so a typo'd or malicious column name can
    never reach SQL construction. Also pins the six-tuple arity."""
    for change in changes:
        if len(change) != 6:
            raise RuntimeError(
                "issue-234 crosswalk rationales: every _CHANGES row must be "
                "(slug, domain, technique_id, column, old, new)"
            )
        slug, _domain, technique_id, column, _old, _new = change
        if column not in _ALLOWED_COLUMNS:
            raise RuntimeError(
                f"issue-234 crosswalk rationales: column {column!r} (slug {slug!r}, "
                f"technique {technique_id!r}) is not in _ALLOWED_COLUMNS; refusing to build "
                "SQL for an unvetted column name"
            )


def _decode(col: str, raw: object) -> object:
    """DB value -> Python value for comparison. JSON columns: None for SQL NULL or the
    JSON literal 'null'; json.loads for a str; passed through unchanged otherwise (a
    backend that already deserializes JSON columns). Text/enum columns: passed through."""
    if col in _JSON_COLUMNS:
        if raw is None or raw == "null":
            return None
        if isinstance(raw, str):
            return json.loads(raw)
        return raw
    return raw


def _encode(col: str, value: object) -> object:
    """Python value -> DB bind value. JSON columns: None stays None (SQL NULL); anything
    else is json.dumps'd. Text/enum columns: passed through unchanged."""
    if col in _JSON_COLUMNS:
        return None if value is None else json.dumps(value)
    return value


def _classify(
    col: str, raw: object, old: object, new: object
) -> Literal["apply", "already", "drift"]:
    """Decode `raw` (the current DB value) and compare to `old`/`new`. `new` is checked
    first: on a fresh DB an inserting migration may already have written `new` from the
    live seed JSON, which must never be mistaken for `old` even if `old` happens to
    parsed-equal `new`'s repr in some degenerate case."""
    current = _decode(col, raw)
    if current == new:
        return "already"
    if current == old:
        return "apply"
    return "drift"


def _group_by_slug(
    changes: tuple[tuple[str, str, str, str, object, object], ...],
) -> dict[str, tuple[tuple[_CellKey, object, object], ...]]:
    """Groups `changes` by slug, preserving each cell's (domain, technique_id, column) key and
    (old, new), and the slugs' first-appearance order (== alphabetical, since `_CHANGES` is
    sorted by (slug, domain, technique_id, column))."""
    groups: dict[str, list[tuple[_CellKey, object, object]]] = {}
    for slug, domain, technique_id, column, old, new in changes:
        groups.setdefault(slug, []).append(((domain, technique_id, column), old, new))
    return {slug: tuple(cells) for slug, cells in groups.items()}


def _classify_slug_group(
    cells: tuple[tuple[_CellKey, object, object], ...],
    found_raw: dict[_CellKey, tuple[bool, object]],
) -> tuple[dict[_CellKey, Literal["apply", "already", "drift"]], tuple[_CellKey, ...]]:
    """Per-slug atomicity (inherited from c7d2e9f4a1b3 -- #209 spec §4.1 amendment M4-1):
    classifies every cell of one slug's group first (`cells` as (key, target_from, target_to)
    -- already direction-adjusted by the caller), then enforces the group guard: if ANY cell
    is genuinely "drift" (found but neither `target_from` nor `target_to`) or its row is
    missing (`found_raw[key][0]` is False), every "apply"-eligible cell in the group is
    reclassified to "drift" too (an "already" cell is left as "already" -- it needs no write
    regardless of its siblings). Returns (final per-cell classification, the cells that were
    genuinely drifted/missing -- the latter is what a caller logs in its one-per-slug warning,
    never the full reclassified set, so the message names only the true anomaly)."""
    raw_classification: dict[_CellKey, Literal["apply", "already", "drift"]] = {}
    for key, target_from, target_to in cells:
        found, raw = found_raw[key]
        raw_classification[key] = (
            "drift" if not found else _classify(key[2], raw, target_from, target_to)
        )
    drifted = tuple(sorted(k for k, cls in raw_classification.items() if cls == "drift"))
    if not drifted:
        return raw_classification, drifted
    final: dict[_CellKey, Literal["apply", "already", "drift"]] = {
        key: ("drift" if cls == "apply" else cls) for key, cls in raw_classification.items()
    }
    return final, drifted


def _as_uuid(value: object) -> uuid.UUID:
    """Normalise a stored id (a uuid.UUID, or the 32-hex / hyphenated string a backend may
    hand back) before re-binding it through a typed sa.Uuid() column."""
    return value if isinstance(value, uuid.UUID) else uuid.UUID(str(value))


def _resolve_entry(bind: sa.engine.Connection, slug: str) -> tuple[uuid.UUID, int] | None:
    row = bind.execute(
        sa.select(_ENTRIES.c.id, _ENTRIES.c.version).where(
            _ENTRIES.c.slug == slug, _ENTRIES.c.version == 1, _ENTRIES.c.source == "seed"
        )
    ).first()
    return None if row is None else (_as_uuid(row[0]), int(row[1]))


def _resolve_mapping_id(
    bind: sa.engine.Connection,
    entry: tuple[uuid.UUID, int] | None,
    domain: str,
    technique_id: str,
) -> uuid.UUID | None:
    """The mapping row's id, or None when the entry, the technique or the mapping row is
    absent (the caller counts that as drift; this never raises)."""
    if entry is None:
        return None
    technique = bind.execute(
        sa.select(_TECHNIQUES.c.id).where(
            _TECHNIQUES.c.technique_id == technique_id, _TECHNIQUES.c.domain == domain
        )
    ).first()
    if technique is None:
        return None
    mapping = bind.execute(
        sa.select(_MAPPINGS.c.id).where(
            _MAPPINGS.c.library_entry_id == entry[0],
            _MAPPINGS.c.library_entry_version == entry[1],
            _MAPPINGS.c.technique_id == _as_uuid(technique[0]),
        )
    ).first()
    return None if mapping is None else _as_uuid(mapping[0])


def _run(reverse: bool) -> None:
    _validate_changes(_CHANGES)
    bind = op.get_bind()
    applied = already = drift = 0
    label = "downgrade" if reverse else "upgrade"
    for slug, cells in sorted(_group_by_slug(_CHANGES).items()):
        dir_cells = tuple((key, (new, old) if reverse else (old, new)) for key, old, new in cells)
        entry = _resolve_entry(bind, slug)
        mapping_ids: dict[_CellKey, uuid.UUID | None] = {}
        found_raw: dict[_CellKey, tuple[bool, object]] = {}
        for key, _targets in dir_cells:
            domain, technique_id, column = key
            mapping_id = _resolve_mapping_id(bind, entry, domain, technique_id)
            mapping_ids[key] = mapping_id
            row = (
                None
                if mapping_id is None
                else bind.execute(
                    sa.select(_MAPPINGS.c[column]).where(_MAPPINGS.c.id == mapping_id)
                ).first()
            )
            found_raw[key] = (row is not None, row[0] if row is not None else None)
        classification, drifted = _classify_slug_group(
            tuple((key, f, t) for key, (f, t) in dir_cells), found_raw
        )
        if drifted:
            logger.warning(
                "issue-234 crosswalk rationales %s: drift in slug=%s; skipping whole slug "
                "(atomic group) -- drifted cell(s): %s",
                label,
                slug,
                ", ".join(f"{technique_id}.{column}" for _domain, technique_id, column in drifted),
            )
        for key, (_f, target_to) in dir_cells:
            cls = classification[key]
            if cls == "already":
                already += 1
            elif cls == "drift":
                drift += 1
            else:
                column = key[2]
                bind.execute(
                    sa.update(_MAPPINGS)
                    .where(_MAPPINGS.c.id == mapping_ids[key])
                    .values(**{column: _encode(column, target_to)})
                )
                applied += 1
    if reverse:
        logger.info(
            "issue-234 crosswalk rationales downgrade: applied=%d already_old=%d drift=%d",
            applied,
            already,
            drift,
        )
    else:
        logger.info(
            "issue-234 crosswalk rationales: applied=%d already_new=%d drift=%d",
            applied,
            already,
            drift,
        )


def upgrade() -> None:
    _run(reverse=False)


def downgrade() -> None:
    _run(reverse=True)
