"""scenario entry currency

Revision ID: be495e8b34d3
Revises: 42c65b63ceeb
Create Date: 2026-06-15 07:39:12.999909

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'be495e8b34d3'
down_revision: Union[str, Sequence[str], None] = '42c65b63ceeb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scenarios', sa.Column('entry_currency', sa.String(length=3), server_default='USD', nullable=False))
    op.add_column('scenarios', sa.Column('entry_rate', sa.Numeric(precision=20, scale=8), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('scenarios', 'entry_rate')
    op.drop_column('scenarios', 'entry_currency')
    # ### end Alembic commands ###
