"""Issue #209: re-map four seed library entries' threat community and re-word all seven
(spec docs/superpowers/specs/2026-10-08-issue-209-community-remap-design.md §3.2).

Same shape as e5f1a9c3d7b2_epic_f_library_curation.py: frozen literals, three-way
per-cell classification against the current DB value (already / apply / drift),
per-slug atomicity, guarded downgrade, pinned counter line. Two tables:
_CHANGES for text/JSON cells and _REMAPS for the community re-maps, whose
community slugs are resolved to (id, version=1) through the threat_communities
table at run time (the v5 UUIDs the P1 migration inserted), never from live model
code. UUIDs are normalised through uuid.UUID(str(x)) before comparison so SQLite's
stored hex form and a hyphenated raw form compare equal.

Revision ID: c7d2e9f4a1b3
Revises: a1c9e4d2b7f0
Create Date: 2026-10-08
"""

from __future__ import annotations

import json
import logging
import uuid
from typing import Literal

import sqlalchemy as sa
from alembic import op

revision = "c7d2e9f4a1b3"
down_revision = "a1c9e4d2b7f0"
branch_labels = None
depends_on = None

logger = logging.getLogger("alembic.runtime.migration")

_ALLOWED_COLUMNS: frozenset[str] = frozenset(
    {"name", "description", "attack_vector", "tags", "canonical_fair_gap"}
)
_JSON_COLUMNS: frozenset[str] = frozenset({"tags"})

# Generated by scripts/build_issue_209_migration_table.py against merge-base
# 7fd06be2 (the adopted main). 17 cells across 7 slugs, sorted by (slug, column).
_CHANGES: tuple[tuple[str, str, object, object], ...] = (
    (
        "accidental-insider-exposure",
        "attack_vector",
        "privileged_access_misuse",
        "misdelivery_or_misconfiguration",
    ),
    (
        "accidental-insider-exposure",
        "description",
        "A non-malicious insider exposes sensitive data through error — emailing a file to the wrong recipient, attaching the wrong document, mis-setting a SharePoint/cloud-share permission, leaving a database or mailbox publicly accessible, or mis-publishing a report. There is no adversary motive; the loss is driven by what was exposed and the resulting breach-notification and regulatory obligations. Miscellaneous errors (misdelivery, misconfiguration, publishing error) are consistently one of the largest breach-cause categories in industry reporting, yet are under-represented relative to attack-driven scenarios in this library.",
        "A non-malicious insider exposes sensitive data through error — emailing a file to the wrong recipient, attaching the wrong document, mis-setting a SharePoint/cloud-share permission, leaving a database or mailbox publicly accessible, or mis-publishing a report. There is no adversary motive; the loss is driven by what was exposed and the resulting breach-notification and regulatory obligations. Miscellaneous errors (misdelivery, misconfiguration, publishing error) are consistently one of the largest breach-cause categories in industry reporting, yet are under-represented relative to attack-driven scenarios in this library. The threat event is the error that would expose the data — counted even when a control catches it, as the accidental-insider counting rule requires — and the loss event is the resulting exposure with its notification, regulatory and remediation cost, whether or not an outsider ever reads the exposed data; an outsider harvesting an exposed store is a separate threat event with its own frequency and community (opportunistic hackers), which the cloud storage misconfiguration entry carries for cloud object storage.",
    ),
    (
        "credential-stuffing-consumer-portal",
        "description",
        "Automated credential stuffing tools (Sentry MBA, Snipr, Openbullet) test username/password combinations from breached credential databases against consumer-facing portals (loyalty accounts, banking, retail, streaming). Successful matches grant account takeover — attackers drain loyalty points, redirect payment instruments, make fraudulent purchases, or sell valid account credentials. Akamai reports credential stuffing as the dominant attack category for retail and financial portals by traffic volume. Low sophistication required; tools and breach databases are commoditized.",
        "Automated credential stuffing tools (Sentry MBA, Snipr, Openbullet) test username/password combinations from breached credential databases against consumer-facing portals (loyalty accounts, banking, retail, streaming). Successful matches grant account takeover — attackers drain loyalty points, redirect payment instruments, make fraudulent purchases, or sell valid account credentials. Akamai reports credential stuffing as the dominant attack category for retail and financial portals by traffic volume. Low sophistication required; tools and breach databases are commoditized. Run as an organised account-takeover operation, with the persistence and monetisation infrastructure behind it, this is the cybercriminals community; an untargeted run against a public login by an unaffiliated individual or small crew, even one that resells what falls out, is the opportunistic hacker's.",
    ),
    (
        "crop-science-ip-exfiltration",
        "description",
        "Competitor-sponsored actors — including nation-state proxies acting on behalf of foreign agri-chemical firms — conduct long-dwell intrusions against crop-science companies (NAICS 325311-325320, 5417) to exfiltrate proprietary seed genetics, pesticide and herbicide formulation data, and precision-agriculture algorithms. Target organizations include major agri-chemical companies (NAICS 325311-325320) and agricultural R&D firms. Loss components include the economic value of the stolen IP (competitive advantage erosion), litigation costs (trade-secret misappropriation under the Defend Trade Secrets Act), and remediation of the intrusion. The long-dwell nature of the attack (months to years before detection) amplifies the IP exposure.",
        "State-directed operators and their proxies, for the benefit of their own state's agri-chemical champions, conduct long-dwell intrusions against crop-science companies (NAICS 325311-325320, 5417) to exfiltrate proprietary seed genetics, pesticide and herbicide formulation data, and precision-agriculture algorithms. Target organizations include major agri-chemical companies (NAICS 325311-325320) and agricultural R&D firms. The sponsorship decides the community: the operators described are state-directed — FBI counterintelligence and DOJ prosecutions document sustained Chinese state targeting of the sector, and the advisory behind the entry's ATT&CK mappings (AA21-200A) documents the intrusion method — while a rival firm acting on its own account, through its own staff or arm's-length recruits, investigators or brokers, is the competitors community instead. Loss components include the economic value of the stolen IP (competitive advantage erosion), litigation costs (trade-secret misappropriation under the Defend Trade Secrets Act), and remediation of the intrusion. The long-dwell nature of the attack (months to years before detection) amplifies the IP exposure.",
    ),
    (
        "crop-science-ip-exfiltration",
        "name",
        "Crop-Science IP Exfiltration — Competitor-Sponsored Theft of Seed Genetics and Agrochemical IP",
        "Crop-Science IP Exfiltration — State-Sponsored Theft of Seed Genetics and Agrochemical IP",
    ),
    (
        "crop-science-ip-exfiltration",
        "tags",
        [
            "food_agriculture",
            "ip_theft",
            "crop_science",
            "seed_genetics",
            "agrochemical",
            "competitors",
            "nation_state_proxy",
            "trade_secret",
        ],
        [
            "food_agriculture",
            "ip_theft",
            "crop_science",
            "seed_genetics",
            "agrochemical",
            "nation_state",
            "nation_state_proxy",
            "trade_secret",
        ],
    ),
    (
        "higher-ed-insider-ddos",
        "description",
        "An enrolled affiliate (a student), motivated by personal grudge, directs an external botnet to launch volumetric distributed denial-of-service attacks against a university's own network - central authentication, registration, and coursework systems - causing repeated availability outages during high-load periods. The attacker is an insider by trust/affiliation, but the DDoS is external and distributed, not conducted through granted network access.",
        "An enrolled affiliate (a student) acting on a personal grudge directs volumetric distributed denial-of-service attacks against a university's own network - central authentication, registration, and coursework systems - causing repeated availability outages during high-load periods such as registration and examinations; the capacity is a botnet the student runs, as in the Rutgers case, or a rented DDoS-for-hire (booter) service. The act is deliberate and uses no granted access, so none of the insider communities applies, and no extortion demand is made. The capability used and the control that matters (DDoS protection) are those of the commercial DDoS entries, which places the entry with cybercriminals; when a booter is rented, its operator is itself a financially motivated criminal acting to disrupt. Its frequency counts only attacks an affiliate directs, through their own botnet or a hired booter; DDoS that criminals mount on their own account, for extortion or otherwise, is a separate scenario with its own frequency.",
    ),
    (
        "higher-ed-insider-ddos",
        "name",
        "Higher-Education Insider-Motivated Botnet DDoS Against Campus Network",
        "Higher-Education DDoS Against Campus Network — Affiliate-Directed Botnet or Booter",
    ),
    (
        "higher-ed-insider-ddos",
        "tags",
        ["education", "higher_education", "ddos", "insider", "availability"],
        [
            "education",
            "higher_education",
            "ddos",
            "botnet",
            "booter",
            "cybercriminals",
            "availability",
        ],
    ),
    (
        "hospitality-guest-data-insider",
        "description",
        "A malicious insider — front-desk staff, reservation agent, or IT employee — abuses privileged access to the property-management system (PMS) or central reservation system to exfiltrate guest personal and payment data for sale or personal use. Hospitality organizations hold dense guest profiles (travel patterns, credit card data, VIP preferences, room-access codes), making them a high-value insider exfiltration target. Loss includes breach notification, PCI-DSS remediation, GDPR/CCPA regulatory fines, and litigation from impacted guests.",
        "A malicious insider with ordinary role access — front-desk staff or a reservation agent — abuses that access to the property-management system (PMS) or central reservation system to exfiltrate guest personal and payment data for sale or personal use; an IT administrator doing the same with elevated rights is the privileged-insider variant. Hospitality organizations hold dense guest profiles (travel patterns, credit card data, VIP preferences, room-access codes), making them a high-value insider exfiltration target. Loss includes breach notification, PCI-DSS remediation, GDPR/CCPA regulatory fines, and litigation from impacted guests.",
    ),
    (
        "insider-ip-theft-manufacturing",
        "attack_vector",
        "privileged_access_misuse",
        "insider_access_abuse",
    ),
    (
        "insider-ip-theft-manufacturing",
        "description",
        "Engineering employee or contractor exfiltrates proprietary manufacturing processes, CAD designs, semiconductor mask sets, chemical formulations, or other trade secrets — often in the context of departure to a competing employer or in response to foreign intelligence tasking. The US Department of Justice prosecutes dozens of such cases annually. Unlike financial-data insider theft, IP theft has a primary loss dominated by competitive advantage loss (difficult to quantify) and a secondary loss dominated by litigation costs and potential criminal investigation exposure.",
        "Engineering employee or contractor exfiltrates proprietary manufacturing processes, CAD designs, semiconductor mask sets, chemical formulations, or other trade secrets — typically on their own initiative ahead of a move to a competing employer. The access abused is ordinary and role-based — the engineer legitimately reads the designs they work on, and no elevated rights are used — which places the entry with the non-privileged insider; an administrator exfiltrating repositories they do not work on is the privileged-insider variant. When a rival solicited the theft it is the competitors community, and when a foreign service tasked it (the cited GE case was charged as economic espionage) the sponsor decides the community, as for crop-science. The US Department of Justice prosecutes dozens of such cases annually. Unlike financial-data insider theft, IP theft has a primary loss dominated by competitive advantage loss (difficult to quantify) and a secondary loss dominated by litigation costs and potential criminal investigation exposure.",
    ),
    (
        "insider-ip-theft-manufacturing",
        "tags",
        ["insider_threat", "ip_theft", "manufacturing", "trade_secrets", "economic_espionage"],
        ["insider_threat", "ip_theft", "manufacturing", "trade_secrets"],
    ),
    (
        "ot-network-scanning-reconnaissance",
        "attack_vector",
        "passive_network_scanning_and_active_probing",
        "network_intrusion",
    ),
    (
        "ot-network-scanning-reconnaissance",
        "canonical_fair_gap",
        "FAIR models threat events as discrete loss-causing incidents; reconnaissance is a pre-incident activity that does not directly cause a loss event but materially increases the probability and magnitude of future attacks. FAIR has no standard mechanism for modeling the value of intelligence delivered to an adversary during reconnaissance as a loss component, nor for modeling how reconnaissance pre-positioning elevates the frequency parameter for future attack archetypes. A two-stage model linking reconnaissance to downstream attack frequency is absent from the canonical taxonomy.",
        "FAIR counts a threat event whether or not it succeeds, and a loss event only when it does. Scanning and protocol enumeration come before any attempt and are not counted here (the nation-state counting rule excludes scans). The counted threat event is a state-directed intrusion attempt — a campaign of access attempts or spearphishing against the organisation — and a successful access or theft of documentation is a loss event, costed as the incident response it forces. FAIR has no loss form for the intelligence an adversary gains, and no canonical mechanism linking pre-positioning to the frequency of a later disruptive attack, so that attack is modelled as its own scenario.",
    ),
    (
        "ot-network-scanning-reconnaissance",
        "description",
        "Nation-state actors and sophisticated threat groups conduct systematic reconnaissance of OT networks using passive scanning (Shodan, Censys), active probing of exposed ICS protocols (Modbus, DNP3, BACnet, EtherNet/IP), and spearphishing for engineering documentation. Volt Typhoon's CISA-documented campaigns (2023-2024) demonstrated persistent pre-positioning reconnaissance in US critical infrastructure OT networks specifically for future disruptive capability. The loss event at the reconnaissance stage is primarily the value of intelligence delivered to the adversary; the downstream loss if reconnaissance enables a follow-on attack is the key risk.",
        "Nation-state actors and sophisticated threat groups prepare disruptive capability against OT networks by attempting access to exposed ICS services (Modbus, DNP3, BACnet, EtherNet/IP), engineering workstations and remote-access paths, and by spearphishing for engineering documentation. Scanning — passive (Shodan, Censys) or active protocol enumeration — is not a threat event under the nation-state counting rule and is not counted; a threat event is one intrusion attempt (a campaign of access attempts or spearphishing against the organisation), counted whether or not it succeeds, so the TEF below is in campaigns per year. Volt Typhoon's CISA-documented campaigns (2023-2024) demonstrated persistent pre-positioning in US critical infrastructure OT networks specifically for future disruptive capability. A loss event is a successful access or theft of documentation; its modelled cost is the incident response it forces, while the loss from any follow-on attack belongs to that attack's own scenario.",
    ),
    (
        "ot-network-scanning-reconnaissance",
        "name",
        "OT Network Scanning and Reconnaissance — Pre-Attack Footprinting",
        "OT Pre-Positioning Reconnaissance — Access Attempts Against Exposed ICS Services",
    ),
)

# (slug, old community slug, new community slug, rationale). Rationale is documentation
# (the curation report repeats it); it is never written to the database.
_REMAPS: tuple[tuple[str, str, str, str], ...] = (
    (
        "crop-science-ip-exfiltration",
        "competitors",
        "nation_state",
        "Sponsorship decides: the operators described are state-directed (FBI/DOJ document sustained "
        "Chinese state targeting of the sector; the entry's ATT&CK mappings rest on CISA/FBI AA21-200A "
        "for the long-dwell intrusion method); a rival acting on its own account, through its own staff "
        "or arm's-length recruits, stays competitors.",
    ),
    (
        "higher-ed-insider-ddos",
        "nonprivileged_insider",
        "cybercriminals",
        "No granted access is used, so the access-based insider counting rules fail; the DDoS capacity "
        "(own botnet, as in the Rutgers exemplar, or a rented booter) and the relevant control match the "
        "commercial DDoS entries under cybercriminals (split-or-lump test); a rented booter operator is "
        "itself a financially motivated criminal acting to disrupt. Targeted, so not opportunistic. "
        "Frequency stays the affiliate-directed rate, stated in the text.",
    ),
    (
        "hospitality-guest-data-insider",
        "privileged_insider",
        "nonprivileged_insider",
        "Front-desk and reservation staff hold ordinary role-based access to the PMS (the non-privileged "
        "profile's definition), not elevated rights; the parallel retail entry is nonprivileged; the "
        "IT-administrator variant is named as the privileged exception.",
    ),
    (
        "insider-ip-theft-manufacturing",
        "privileged_insider",
        "nonprivileged_insider",
        "The engineer's access to the designs they work on is ordinary and role-based; no elevated rights "
        "are used. Sponsored theft (rival-solicited: competitors; state-tasked: the sponsor decides) is "
        "stated as out of this entry's scope.",
    ),
)

_TABLE = sa.table(
    "scenario_library_entries",
    *[sa.column(c) for c in sorted(_ALLOWED_COLUMNS)],
    sa.column("threat_community_id"),
    sa.column("threat_community_version"),
    sa.column("slug"),
    sa.column("version"),
    sa.column("source"),
)
_TC = sa.table("threat_communities", sa.column("id"), sa.column("version"), sa.column("slug"))


# --- copied verbatim from alembic/versions/e5f1a9c3d7b2_epic_f_library_curation.py ---
# _validate_changes, _decode, _encode, _classify, _group_by_slug, _classify_slug_group
# (same bodies; only the RuntimeError prefix becomes "issue-209 community remaps:").
# --------------------------------------------------------------------------------


def _validate_changes(changes: tuple[tuple[str, str, object, object], ...]) -> None:
    """Every column name in `changes` must be a vetted literal from
    _ALLOWED_COLUMNS -- an explicit raise, never an assert (assertions are
    stripped under `python -O`), so a typo'd or malicious column name can
    never reach SQL construction."""
    for slug, column, _old, _new in changes:
        if column not in _ALLOWED_COLUMNS:
            raise RuntimeError(
                f"issue-209 community remaps: column {column!r} (slug {slug!r}) is not in "
                "_ALLOWED_COLUMNS; refusing to build SQL for an unvetted column name"
            )


def _decode(col: str, raw: object) -> object:
    """DB value -> Python value for comparison. JSON columns: None for SQL NULL or the
    JSON literal 'null'; json.loads for a str; passed through unchanged otherwise (a
    backend that already deserializes JSON columns). Text/enum columns: passed through."""
    if col in _JSON_COLUMNS:
        if raw is None or raw == "null":
            return None
        if isinstance(raw, str):
            return json.loads(raw)
        return raw
    return raw


def _encode(col: str, value: object) -> object:
    """Python value -> DB bind value. JSON columns: None stays None (SQL NULL); anything
    else is json.dumps'd. Text/enum columns: passed through unchanged."""
    if col in _JSON_COLUMNS:
        return None if value is None else json.dumps(value)
    return value


def _classify(
    col: str, raw: object, old: object, new: object
) -> Literal["apply", "already", "drift"]:
    """Decode `raw` (the current DB value) and compare to `old`/`new`. `new` is checked
    first: on a fresh DB an inserting migration may already have written `new` from the
    live seed JSON, which must never be mistaken for `old` even if `old` happens to
    parsed-equal `new`'s repr in some degenerate case."""
    current = _decode(col, raw)
    if current == new:
        return "already"
    if current == old:
        return "apply"
    return "drift"


def _group_by_slug(
    changes: tuple[tuple[str, str, object, object], ...],
) -> dict[str, tuple[tuple[str, object, object], ...]]:
    """Groups `changes` by slug, preserving each cell's (column, old, new) and the
    slugs' first-appearance order (== alphabetical, since `_CHANGES` is sorted by
    (slug, column))."""
    groups: dict[str, list[tuple[str, object, object]]] = {}
    for slug, column, old, new in changes:
        groups.setdefault(slug, []).append((column, old, new))
    return {slug: tuple(cells) for slug, cells in groups.items()}


def _classify_slug_group(
    cells: tuple[tuple[str, object, object], ...],
    found_raw: dict[str, tuple[bool, object]],
) -> tuple[dict[str, Literal["apply", "already", "drift"]], tuple[str, ...]]:
    """Per-slug atomicity (spec §4.1 amendment, M4-1): classifies every cell of one
    slug's group first (`cells` as (column, target_from, target_to) -- already
    direction-adjusted by the caller), then enforces the group guard: if ANY cell is
    genuinely "drift" (found but neither `target_from` nor `target_to`) or its row is
    missing (`found_raw[column][0]` is False), every "apply"-eligible cell in the group
    is reclassified to "drift" too (an "already" cell is left as "already" -- it needs
    no write regardless of its siblings). Returns (final per-column classification,
    the columns that were genuinely drifted/missing -- the latter is what a caller logs
    in its one-per-slug warning, never the full reclassified set, so the message names
    only the true anomaly)."""
    raw_classification: dict[str, Literal["apply", "already", "drift"]] = {}
    for column, target_from, target_to in cells:
        found, raw = found_raw[column]
        raw_classification[column] = (
            "drift" if not found else _classify(column, raw, target_from, target_to)
        )
    drifted_columns = tuple(sorted(c for c, cls in raw_classification.items() if cls == "drift"))
    if not drifted_columns:
        return raw_classification, drifted_columns
    final: dict[str, Literal["apply", "already", "drift"]] = {
        column: ("drift" if cls == "apply" else cls) for column, cls in raw_classification.items()
    }
    return final, drifted_columns


def _norm_uuid(value: object) -> str | None:
    """Stored UUID (hex, hyphenated, bytes or uuid.UUID) -> canonical hex, or None."""
    if value is None:
        return None
    if isinstance(value, uuid.UUID):
        return value.hex
    if isinstance(value, bytes):
        return uuid.UUID(bytes=value).hex
    return uuid.UUID(str(value)).hex


def _community_ids(bind: sa.engine.Connection) -> dict[str, str]:
    """slug -> canonical hex id of the version-1 row of every community named in _REMAPS;
    raises if one is missing (a DB without the P1 seed cannot be re-mapped)."""
    wanted = {s for _e, old, new, _r in _REMAPS for s in (old, new)}
    rows = bind.execute(
        sa.select(_TC.c.slug, _TC.c.id).where(_TC.c.version == 1, _TC.c.slug.in_(sorted(wanted)))
    ).all()
    ids = {slug: _norm_uuid(cid) for slug, cid in rows}
    missing = wanted - {k for k, v in ids.items() if v is not None}
    if missing:
        raise RuntimeError(
            f"issue-209 community remaps: threat_communities v1 rows missing for {sorted(missing)}"
        )
    return {k: v for k, v in ids.items() if v is not None}


def _where(slug: str) -> tuple[sa.ColumnElement[bool], ...]:
    return (_TABLE.c.slug == slug, _TABLE.c.version == 1, _TABLE.c.source == "seed")


def _run(reverse: bool) -> None:
    _validate_changes(_CHANGES)
    bind = op.get_bind()
    ids = _community_ids(bind)
    applied = already = drift = 0
    label = "downgrade" if reverse else "upgrade"
    # One cell list per slug: text cells carry their column; a re-map carries the pseudo-column
    # "threat_community_id" with canonical hex ids as old/new.
    cells_by_slug: dict[str, list[tuple[str, object, object]]] = {}
    for slug, column, old, new in _CHANGES:
        cells_by_slug.setdefault(slug, []).append((column, old, new))
    for slug, old_slug, new_slug, _r in _REMAPS:
        cells_by_slug.setdefault(slug, []).append(
            ("threat_community_id", ids[old_slug], ids[new_slug])
        )
    for slug, cells in sorted(cells_by_slug.items()):
        dir_cells = tuple(
            (column, (new, old) if reverse else (old, new)) for column, old, new in cells
        )
        found_raw: dict[str, tuple[bool, object]] = {}
        for column, _targets in dir_cells:
            row = bind.execute(sa.select(_TABLE.c[column]).where(*_where(slug))).first()
            raw = row[0] if row is not None else None
            if column == "threat_community_id":
                raw = _norm_uuid(raw)
            found_raw[column] = (row is not None, raw)
        classification, drifted = _classify_slug_group(
            tuple((column, f, t) for column, (f, t) in dir_cells), found_raw
        )
        if drifted:
            logger.warning(
                "issue-209 community remaps %s: drift in slug=%s; skipping whole slug "
                "(atomic group) -- drifted column(s): %s",
                label,
                slug,
                ", ".join(drifted),
            )
        for column, (_f, target_to) in dir_cells:
            cls = classification[column]
            if cls == "already":
                already += 1
            elif cls == "drift":
                drift += 1
            else:
                values: dict[str, object]
                if column == "threat_community_id":
                    values = {"threat_community_id": target_to, "threat_community_version": 1}
                else:
                    values = {column: _encode(column, target_to)}
                bind.execute(sa.update(_TABLE).where(*_where(slug)).values(**values))
                applied += 1
    if reverse:
        logger.info(
            "issue-209 community remaps downgrade: applied=%d already_old=%d drift=%d",
            applied,
            already,
            drift,
        )
    else:
        logger.info(
            "issue-209 community remaps: applied=%d already_new=%d drift=%d",
            applied,
            already,
            drift,
        )


def upgrade() -> None:
    _run(reverse=False)


def downgrade() -> None:
    _run(reverse=True)
