"""security_settings

Revision ID: e4636e6fb4eb
Revises: 2c855aa93044
Create Date: 2026-07-23 17:41:58.515995

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e4636e6fb4eb'
down_revision: Union[str, Sequence[str], None] = '2c855aa93044'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('security_settings',
    sa.Column('mfa_policy', sa.String(length=16), nullable=True),
    sa.Column('step_up_window_seconds', sa.Integer(), nullable=True),
    sa.Column('step_up_exports', sa.Boolean(), nullable=True),
    sa.Column('step_up_destructive', sa.Boolean(), nullable=True),
    sa.Column('step_up_admin', sa.Boolean(), nullable=True),
    sa.Column('step_up_credentials', sa.Boolean(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', name='uq_security_settings_org')
    )
    op.create_index(op.f('ix_security_settings_organization_id'), 'security_settings', ['organization_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_security_settings_organization_id'), table_name='security_settings')
    op.drop_table('security_settings')
    # ### end Alembic commands ###
