"""subject_matter_experts and estimates and version_token

Revision ID: ed70de5aa6b9
Revises: 08358cf073b8
Create Date: 2026-05-24 15:21:42.487015

Phase: evaluator-style wizard step 3, Task 2/11.

Creates:
- ``subject_matter_experts`` (per-org SME directory) with:
  - ``email_lower`` DB-COMPUTED via ``sa.Computed("lower(email)",
    persisted=True)`` so per-org uniqueness ignores casing without
    requiring an application-layer normalisation pass (Arch-14 / Arch-24).
  - Partial unique indexes via ``sqlite_where=`` + ``postgresql_where=``
    (Arch-19 — probe at ``tests/test_sqlite_partial_index_probe.py``
    confirmed SQLite honours the predicate):
    - ``ux_sme_org_email_live`` — at most one live, non-archived,
      user-owned row per (org, email_lower).
    - ``ux_sme_org_system_owned`` — at most one system-owned IRIS-anchor
      SME per org (Arch-15; required for T3's ``get_or_create_iris_sme``
      ON CONFLICT path).
    - ``ix_sme_org_name`` — non-unique browsing index for the SME picker.
  - CHECK constraints (Spec-30 + Arch-7):
    - ``ck_sme_created_via_enum`` — restricts ``created_via`` to the
      4-value enum {admin, analyst_request, analyst_request_rejected,
      system}; explicit CHECK rather than native enum to keep cross-DB.
    - ``ck_sme_system_or_user_owned`` — system-owned rows MUST have
      ``created_by IS NULL`` and user-owned rows MUST have
      ``created_by IS NOT NULL``.
- ``scenario_sme_estimates`` (per scenario × fieldset × SME bounds) with:
  - ``ScenarioFieldset`` cross-DB enum (``Enum(..., native_enum=False)``).
  - CHECK constraints (Spec-9):
    - ``ck_sse_low_positive`` (``low > 0``).
    - ``ck_sse_high_ge_low`` (``high >= low``).
    - ``ck_sse_vuln_upper_bound`` — Vulnerability fieldset must stay in
      [0, 1] (FAIR-CAM bound).

Modifies:
- ``wizard_drafts.version_token`` (Sec-18) — server_default '0' so the
  migration is safe against any existing rows in shared dev DBs / non-
  fresh deployments; nullable=False after backfill.
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ed70de5aa6b9'
down_revision: Union[str, Sequence[str], None] = '08358cf073b8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subject_matter_experts',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=True),
    sa.Column('email_lower', sa.String(length=320), sa.Computed('lower(email)', persisted=True), nullable=True),
    sa.Column('role_title', sa.String(length=200), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('archived_at', sa.DateTime(), nullable=True),
    sa.Column('archived_by', sa.Uuid(), nullable=True),
    sa.Column('is_system_owned', sa.Boolean(), nullable=False),
    sa.Column('pending_review', sa.Boolean(), nullable=False),
    sa.Column('created_via', sa.String(length=40), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.CheckConstraint("created_via IN ('admin', 'analyst_request', 'analyst_request_rejected', 'system')", name='ck_sme_created_via_enum'),
    sa.CheckConstraint('(is_system_owned = TRUE AND created_by IS NULL) OR (is_system_owned = FALSE AND created_by IS NOT NULL)', name='ck_sme_system_or_user_owned'),
    sa.ForeignKeyConstraint(['archived_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_sme_org_name', 'subject_matter_experts', ['organization_id', 'name'], unique=False, sqlite_where=sa.text('archived_at IS NULL'), postgresql_where=sa.text('archived_at IS NULL'))
    op.create_index(op.f('ix_subject_matter_experts_organization_id'), 'subject_matter_experts', ['organization_id'], unique=False)
    op.create_index('ux_sme_org_email_live', 'subject_matter_experts', ['organization_id', 'email_lower'], unique=True, sqlite_where=sa.text('email_lower IS NOT NULL AND archived_at IS NULL AND is_system_owned = 0'), postgresql_where=sa.text('email_lower IS NOT NULL AND archived_at IS NULL AND is_system_owned = FALSE'))
    op.create_index('ux_sme_org_system_owned', 'subject_matter_experts', ['organization_id'], unique=True, sqlite_where=sa.text('is_system_owned = 1'), postgresql_where=sa.text('is_system_owned = TRUE'))
    op.create_table('scenario_sme_estimates',
    sa.Column('scenario_id', sa.Uuid(), nullable=False),
    sa.Column('fieldset', sa.Enum('TEF', 'VULN', 'PL', 'SL', name='scenario_fieldset', native_enum=False), nullable=False),
    sa.Column('sme_id', sa.Uuid(), nullable=False),
    sa.Column('low', sa.Float(), nullable=False),
    sa.Column('high', sa.Float(), nullable=False),
    sa.Column('recorded_at', sa.DateTime(), nullable=False),
    sa.Column('recorded_by', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.CheckConstraint("fieldset != 'vuln' OR (low <= 1.0 AND high <= 1.0)", name='ck_sse_vuln_upper_bound'),
    sa.CheckConstraint('high >= low', name='ck_sse_high_ge_low'),
    sa.CheckConstraint('low > 0', name='ck_sse_low_positive'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['recorded_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['scenario_id'], ['scenarios.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sme_id'], ['subject_matter_experts.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scenario_sme_estimates_organization_id'), 'scenario_sme_estimates', ['organization_id'], unique=False)
    op.create_index(op.f('ix_scenario_sme_estimates_scenario_id'), 'scenario_sme_estimates', ['scenario_id'], unique=False)
    op.create_index(op.f('ix_scenario_sme_estimates_sme_id'), 'scenario_sme_estimates', ['sme_id'], unique=False)
    op.create_index('ix_sse_scenario_fieldset', 'scenario_sme_estimates', ['scenario_id', 'fieldset'], unique=False)
    op.add_column(
        'wizard_drafts',
        sa.Column(
            'version_token',
            sa.Integer(),
            nullable=False,
            server_default='0',
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('wizard_drafts', 'version_token')
    op.drop_index('ix_sse_scenario_fieldset', table_name='scenario_sme_estimates')
    op.drop_index(op.f('ix_scenario_sme_estimates_sme_id'), table_name='scenario_sme_estimates')
    op.drop_index(op.f('ix_scenario_sme_estimates_scenario_id'), table_name='scenario_sme_estimates')
    op.drop_index(op.f('ix_scenario_sme_estimates_organization_id'), table_name='scenario_sme_estimates')
    op.drop_table('scenario_sme_estimates')
    op.drop_index('ux_sme_org_system_owned', table_name='subject_matter_experts', sqlite_where=sa.text('is_system_owned = 1'), postgresql_where=sa.text('is_system_owned = TRUE'))
    op.drop_index('ux_sme_org_email_live', table_name='subject_matter_experts', sqlite_where=sa.text('email_lower IS NOT NULL AND archived_at IS NULL AND is_system_owned = 0'), postgresql_where=sa.text('email_lower IS NOT NULL AND archived_at IS NULL AND is_system_owned = FALSE'))
    op.drop_index(op.f('ix_subject_matter_experts_organization_id'), table_name='subject_matter_experts')
    op.drop_index('ix_sme_org_name', table_name='subject_matter_experts', sqlite_where=sa.text('archived_at IS NULL'), postgresql_where=sa.text('archived_at IS NULL'))
    op.drop_table('subject_matter_experts')
    # ### end Alembic commands ###
