"""Regression: pre-commit lint forbids inline-dict flash.

r3 MAJOR (security #10) — depth upgrade. r2 only ran a bare ``grep`` against
tmp_path which proved nothing about the pre-commit hook itself. r3 ships
TWO tests:

1. SMOKE (always runs) — grep against tmp_path. Cheap; catches the case
   where someone deletes the linter entry from .pre-commit-config.yaml.
2. CI-ONLY (``@pytest.mark.ci_only``) — runs ``pre-commit run`` as a
   subprocess against a fixture file. Exercises the actual hook wiring;
   the smoke test above can't catch regressions in the entry script
   (e.g. someone fixes the pattern but breaks the bash one-liner).

The CI-only marker keeps the hot dev loop fast (no fork-and-exec on every
``pytest -q``); CI runs both."""

from __future__ import annotations

import subprocess
import sys
from pathlib import Path

import pytest

PROJECT_ROOT = Path(__file__).resolve().parents[2]


def test_forbid_inline_flash_dict_lint_fires_on_violation_smoke(tmp_path: Path) -> None:
    """Smoke: plant a fixture file with the forbidden pattern; assert grep finds it."""
    fixture = tmp_path / "violation.py"
    fixture.write_text('payload = {"flash": {"message": "x", "level": "info"}}\n')
    proc = subprocess.run(
        ["grep", "-rn", '"flash": *{', str(tmp_path)],
        capture_output=True,
        text=True,
    )
    assert proc.returncode == 0  # grep found a match
    assert "violation.py" in proc.stdout


@pytest.mark.ci_only
def test_forbid_inline_flash_dict_lint_fires_via_precommit() -> None:
    """Real subprocess invocation of the pre-commit hook against a planted violation.

    The hook has pass_filenames: false + always_run: true and hardcodes
    `grep -rn "..." src/idraa/`. To exercise the wiring we plant a
    short-lived violation file inside the real src/idraa/ tree (with
    try/finally teardown) so the hook's grep actually finds it.
    """
    violation = PROJECT_ROOT / "src" / "idraa" / "_flash_lint_test_violation.py"
    assert not violation.exists(), f"stale test artifact at {violation} — delete and retry"
    violation.write_text(
        "# generated by test_flash_lint_regression — auto-cleaned in finally\n"
        "def _violation_demo() -> dict:\n"
        '    return {"flash": {"message": "x", "level": "info"}}\n'
    )
    try:
        result = subprocess.run(
            # sys.executable -m pre_commit: bare "pre-commit" is PATH-dependent
            # (lives in .venv/bin/, absent from the shell PATH in fresh
            # worktrees) — the module form always resolves to the venv that is
            # running the test.
            [sys.executable, "-m", "pre_commit", "run", "forbid-inline-flash-dict", "--all-files"],
            capture_output=True,
            text=True,
            cwd=str(PROJECT_ROOT),
        )
    finally:
        violation.unlink(missing_ok=True)
    assert result.returncode != 0, (
        "pre-commit lint failed to fire on inline flash dict.\n"
        f"stdout: {result.stdout}\nstderr: {result.stderr}"
    )
