"""Policy tests for scripts/sca_gate.py (supply-chain epic #555)."""

import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent.parent / "scripts"))
import sca_gate
from sca_gate import (  # ruff's E402 exempts sys.path.insert idioms
    evaluate,
    parse_suppressions,
    partition_export,
)


def _vuln(pkg, vid, fixes):
    return {"name": pkg, "vulns": [{"id": vid, "fix_versions": fixes}]}


def test_fixable_unsuppressed_fails():
    failures, warnings = evaluate([_vuln("foo", "GHSA-xxxx", ["1.2.3"])], set())
    assert len(failures) == 1 and not warnings


def test_unfixable_warns():
    failures, warnings = evaluate([_vuln("foo", "GHSA-yyyy", [])], set())
    assert not failures and len(warnings) == 1


def test_suppressed_fixable_warns_not_fails():
    failures, warnings = evaluate([_vuln("foo", "GHSA-xxxx", ["1.2.3"])], {"GHSA-xxxx"})
    assert not failures and len(warnings) == 1


def test_parse_suppressions_requires_reason_comment(tmp_path):
    f = tmp_path / "s.txt"
    f.write_text("# reason: unfixable transitive; review-by 2026-10-01\nGHSA-zzzz\n\n")
    assert parse_suppressions(f) == {"GHSA-zzzz"}


def test_bare_suppression_id_raises(tmp_path):
    import pytest

    f = tmp_path / "s.txt"
    f.write_text("GHSA-bare\n")
    with pytest.raises(ValueError, match="lacks a reason comment"):
        parse_suppressions(f)


_EXPORT = """\
# This file was autogenerated by uv via the following command:
-e .
-e ./fair_cam
anyio==4.14.2 ; python_full_version < '3.15'
    # via idraa
anyio==4.15.1 ; python_full_version >= '3.15'
tzdata==2026.1 ; sys_platform == 'win32'
Jinja2==3.1.6
psycopg[binary]==3.2.9 ; sys_platform != 'win32'
"""


def test_partition_export_audits_every_marker_fork():
    # #182: pip-audit drops lines whose marker misses the running interpreter,
    # so the >=3.15 fork and the win32-only pin were never audited.
    layers = partition_export(_EXPORT)
    flat = [pin for layer in layers for pin in layer]
    assert sorted(flat) == sorted(
        [
            "anyio==4.14.2",
            "anyio==4.15.1",
            "tzdata==2026.1",
            "Jinja2==3.1.6",
            "psycopg[binary]==3.2.9",
        ]
    )
    assert not any(";" in pin for pin in flat)


def test_partition_export_never_pins_one_package_twice_per_layer():
    # pip-audit rejects duplicate requirements in one file.
    layers = partition_export(_EXPORT)
    assert len(layers) == 2
    for layer in layers:
        names = [pin.split("==")[0].split("[")[0].lower() for pin in layer]
        assert len(names) == len(set(names))
    assert layers[1] == ["anyio==4.15.1"]


def test_partition_export_skips_local_editables_and_comments():
    assert partition_export("-e .\n# via x\n./fair_cam\n\n") == []


def _drive_main(monkeypatch, export_text, audit):
    """Run main() with the uv export and each pip-audit layer stubbed."""
    import json
    import subprocess

    def fake_run(argv, **kwargs):
        Path(argv[argv.index("-o") + 1]).write_text(export_text)
        return subprocess.CompletedProcess(argv, 0)

    def fake_audit(pins):
        deps = audit(pins)
        code = 1 if any(d.get("vulns") for d in deps) else 0
        return subprocess.CompletedProcess([], code, stdout=json.dumps({"dependencies": deps}))

    monkeypatch.setattr(sca_gate.subprocess, "run", fake_run)
    monkeypatch.setattr(sca_gate, "_audit", fake_audit)
    return sca_gate.main()


def _clean_except(bad_pin):
    def audit(pins):
        return [
            {"name": p.split("==")[0], "version": p.split("==")[1]}
            | (
                {"vulns": [{"id": "GHSA-fork", "fix_versions": ["9"]}]}
                if p == bad_pin
                else {"vulns": []}
            )
            for p in pins
        ]

    return audit


def test_main_fails_on_vuln_hidden_behind_non_matching_marker(monkeypatch, capsys):
    # #182 end to end: the old gate never sent the >=3.15 fork to pip-audit.
    rc = _drive_main(monkeypatch, _EXPORT, _clean_except("anyio==4.15.1"))
    assert rc == 1
    assert "anyio: GHSA-fork" in capsys.readouterr().out


def test_main_fails_closed_on_skipped_pin(monkeypatch):
    def audit(pins):
        return [{"name": p.split("==")[0], "skip_reason": "not on PyPI"} for p in pins]

    assert _drive_main(monkeypatch, _EXPORT, audit) == 2


def test_main_fails_closed_on_dropped_pin(monkeypatch):
    assert _drive_main(monkeypatch, _EXPORT, lambda pins: []) == 2


def test_main_fails_closed_on_empty_export(monkeypatch):
    assert _drive_main(monkeypatch, "-e .\n", _clean_except(None)) == 2


def test_main_passes_clean_export(monkeypatch):
    assert _drive_main(monkeypatch, _EXPORT, _clean_except(None)) == 0
